### ISSUE TITLE
Handle omission of `version` field in dependency coordinates

### ISSUE THREAD

**Issue by serebit** [jmfayard/refreshVersions#109]
**Is your feature request related to a problem? Please describe.**
The fact that I either have to use a version of `+` or a dummy version for my dependencies isn't exactly ideal. It's a little confusing to people who are viewing my repository that the versions I'm providing in the `dependencies` block aren't actually being used.
 
**Describe the solution you'd like**
I'd like to be able to omit the `version` field entirely from my dependencies, for the purpose of clarity.

**Describe alternatives you've considered**
¯\\\_(ツ)\_/¯

**Additional context**
I'm not sure how feasible this is with Gradle's architecture, but I figured I'd make the feature request anyway, since I couldn't find an issue on the topic.

**Comment by jmfayard** [comment]
@serebit I agree with your point. 
An alternative is to use `_` like in Kotlin, meaning it's unused. It works, unless you are using Android Studio, which is stupid and that makes the Sync fails. 
If you are doing Android development, I have for now nothing better to propose that adding a **comment** to warn the developer that the real versions are to be found in `gradle.properteis`

**Comment by serebit** [comment]
Good thing I don't do Android development, then! Thanks for the tip.

**Comment by jmfayard** [comment]
@serebit wait, I did a quick test

Assuming you have already run `:refreshVersions`, simply removing the version seems to work.

```
plugins {
    id("de.fayard.buildSrcVersions") // remove version
}

dependencies {
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7")
}
``

Can you confirm that's also the case for you?
Run `./gradlew dependencies`

**Comment by serebit** [comment]
Nope, doesn't work. In addition, the `_` version only works for dependencies with jarfiles. Kotlin multiplatform `metadata` dependencies simply fail to resolve.

**Comment by jmfayard** [comment]
Thanks. Well then I'm like you, I would like something more explicit but how? ¯_(ツ)_/¯

**Comment by jmfayard** [comment]
refreshVersions will use `_` as a placeholder _and_ support new Gradle 6 dependencies features where you remove the versions after you added platform constraints from a BOM or gradle metatdata
