### ISSUE TITLE
is buildSrcVersions gone?

### ISSUE THREAD

**Issue by DanySK** [jmfayard/refreshVersions#119]
I tried to switch to the new naming system:

```kotlin
plugins {
    id("de.fayard.refreshVersions") version "0.7.0"
}
```

If I use version `0.7.0`, I can run the `buildSrcVersions` task flawlessly. It also proposes an upgrade to `0.8.1`. If do so, however, buildSrcVersions is no longer available as task.

* Are de.fayard.buildSrcVersions and de.fayard.refreshVersions the same plugin, as the guide seems to suggest?
* Am I supposed to stay with de.fayard.buildSrcVersions if I want to keep on using the buildSrcVersions task?
* Has the task got renamed? Has it been dropped completely?

**Comment by jmfayard** [comment]
Hello @DanySK 
[my plan for 1.0 is to focus on gradle refreshVersions](https://github.com/jmfayard/buildSrcVersions/issues/104)

It means a few different things:

- `id("de.fayard.refreshVersions") version "0.8.1" }` and better to not have the buildSrcVersions task anymore
- Declaring the versions numbers not in code but in a proper tooling-friendly file format `versions.properties` is better than using `buildSrc/src/main/Versions.kt`
-  Having a file `buildSrc/src/main/Libs.kt` to use auto-complete is however a good idea. But if you think about it, the buildSrc is a private Gradle plugin. Why not a public Gradle plugin that contains the magic dependencies strings that are commonly used. I am working with @LouisCAD on this
- Things are evolving fast and I suggest to stay for now `id("de.fayard.buildSrcVersions") version "0.7.0" }` if you are using the task buildSrcVersions

The README needs to be updated to reflect this but I am on vacation right now

**Comment by DanySK** [comment]
Hi @jmfayard 
thanks for the answer. I was confused by the readme, which said the plugins were supposed to be the same. I'll stick to buildSrc for now, looking forward to the new infrastructure.

If my understanding is correct, there will be a Gradle plugin for generating/accessing compile-time shorthands for libraries (the great work `Libs.kt` is doing now), while versions will be dealt with using `refreshVersions`.
Is that correct?

Do you foresee major changes to the format of the file produced by refreshVersions?

**Comment by jmfayard** [comment]
@DanySK you are correct.
The file will be a Java properties file called `versions.properties`
The major change planned will be only if Gradle itself introduces its own file format for declaring properties, as I learned they would like to do. Then of course we will switch to that

**Comment by martinbonnin** [comment]
I just got bit by that as well and started updating the README (https://github.com/jmfayard/buildSrcVersions/pull/133) before realising it might require more than a few fixes. @jmfayard should I try to update the README to make it closer to the latest release ?

**Comment by martinbonnin** [comment]
Should this issue be closed ?

**Comment by LouisCAD** [comment]
I'm leaving it closed as we need to document refreshVersions better and keep an overview document on what changed and why, for history.

**Comment by jmfayard** [comment]
Duplicate on https://github.com/jmfayard/refreshVersions/issues/235
