### ISSUE TITLE
Kotlin multiplatform dependencies fail to apply versions from gradle.properties

### ISSUE THREAD

**Issue by serebit** [jmfayard/refreshVersions#120]
**Checklist**

- [x] I verified that the task `./gradlew :dependencyUpdates` works correctly. If that's not the case, it's better to submit a bug-report to https://github.com/ben-manes/gradle-versions-plugin 
- [x] I tried to reproduce the bug within `sample-groovy`, `sample-kotlin` or `sample-versionsOnlyMode` 
- [x] I have run with `$ ./gradlew --scan buildSrcVersions` or `$./gradlew --scan refreshVersions` to [provide a Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg)
 
**Describe the bug**

When a project uses the `kotlin-multiplatform` plugin and declares dependencies on multiplatform projects, such as `kotlinx-coroutines-core-native`, the plugin fails to apply those dependencies' versions from the `gradle.properties` file. When running the `dependencies` task in such a project, for example, the following warnings are shown by Gradle for a project with a dependency on `org.jetbrains.kotlinx:kotlinx-coroutines-core-native` and a placeholder version of `+`:
```
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core-native:+ -> 1.3.2-1.3.60-eap-76
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core-common:1.3.2-1.3.60-eap-76
|         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.60-eap-76 -> 1.3.50
```
Despite the version in `gradle.properties` being `1.3.50`, Gradle uses the `+` version. 

**To Reproduce**

- Clone a repository with a dependency on a Kotlin multiplatform artifact, such as `kotlinx-coroutines-core-native` or `ktor-client-core-native`, that uses the `refreshVersions` plugin
- Run the `dependencies` task to see if the version in `gradle.properties` matches the version that Gradle uses

**Expected behavior**
The plugin should correctly apply the versions in `gradle.properties` to all dependencies, including Kotlin multiplatform dependencies

**Comment by LouisCAD** [comment]
Hi, we are reworking the plugin significantly. The next version will feature a way to try the experimental updater, which will become the only one in the future.

This experimental updater has been done to play well with dependencies having mutually exclusive gradle metadata (like with Kotlin multiplatform), and also for other reasons which have been explained in #104.

Once the release is out there, we will ask you to try the experimental updater, it should fix your issue, and if not, we should be able to fix it.

**Comment by jmfayard** [comment]
I think this is obsolete
