### ISSUE TITLE
Bootstraping refreshVersions

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#155]
**Context**

We have a chicken-and-egg problem on how to tell Gradle that plugins versions should be found in `versions.properties`. 

**Describe the solution you'd like**

The setup for Groovy should now be:

```groovy
// settings.gradle
import de.fayard.versions.RefreshVersionsSetup
buildscript {
        dependencies.classpath("de.fayard:refreshVersions:VERSION")
}
RefreshVersionsSetup.bootstrap(settings)
```

The setup for Kotlin should now be:

```kotlin
// settings.gradle.kts
import de.fayard.versions.bootstrapRefreshVersions

buildscript {
    dependencies.classpath("de.fayard:refreshVersions:VERSION")
}

settings.bootstrapRefreshVersions()
```

**Describe alternatives you've considered**

- users write tons of boilerplate in `settings.gradle`
- the plugin copy/paste that boilerplate in the `gradle` folder
- we try to use the `plugins` block in settings.gradle

none of this is nice or works with Gradle 5-6

The best solution so far was found by @LouisCAD: using the classpath inside `settings.gradle`

https://github.com/jmfayard/refreshVersions/blob/a20c43b071a0e17eb92545710ec89df8c562796a/sample-groovy/settings.gradle#L1-L19

Biggest drawback of this solution: the bootstrap function is tied to the version of the plugin. This makes updating `refreshVersions` itself potentially unsafe, and at least not as easy as the other plugins.

**Comment by LouisCAD** [comment]
Resolved in version 0.9.1
