### ISSUE TITLE
refreshVersions expect dependencies with a version placeholder _

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#160]
URL for the warning in the  plugin

TODO: @LouisCAD explains why?

**Comment by LouisCAD** [comment]
This is not an issue, but normal behavior. If we want to document it, we should put it as documentation in the main repository, and have a way to ensure we have a stable link to it (tagging can work for a readable permalink).

It's important that we keep issues clean so we can focus on actual issues when needed, and can triage them easily.

I'm letting this one open until we have a documentation explaining why we use a version placeholder. I'll probably work on it myself soon, before the 5th of march 2020.

**Comment by dsvensson** [comment]
How to solve if this is caused by `kotlin-scripting-compiler-embeddable`? It's not something I import explicitly.
