### ISSUE TITLE
Semi-automatic migration

### ISSUE THREAD

**Issue by martinbonnin** [jmfayard/refreshVersions#169]
For big projects, the migration can be time consuming. 
It would be great if this could be automated.

**Comment by LouisCAD** [comment]
Not everything can be automated, but this is my top priority right now. I'll focus on supporting it for Gradle Kotlin DSL first. You can see the priority list at any time [here](https://github.com/jmfayard/refreshVersions/projects/4) and you can let us know if you believe the order should be changed for given reasons.

**Comment by LouisCAD** [comment]
## What can be improved in the existing migration task
1. Ergonomics (Don't require to type a full word to validate migration of a single dependency)
2. Keep track of what has been migrated already to not show out of sync hardcoded dependencies count
3. Automatically replace dependency notations in the build files when possible safely
4. Have better rules to ignore dependencies added by plugins (e.g. "kotlin-android-extensions" plugin)
5. Its name (remove lengthy `migrateToRefreshVersionsDependenciesConstants ` and have a `--migrate` flag to `refreshVersions` redirect to it instead)

**Comment by LouisCAD** [comment]
After some discussion, here's the approach we are considering:
- Automatic migration for hardocoded dependencies (including with string templates or GString)
- Semi-automatic migration for remaining distinct dependencies, without having to dive into each module and each of its Gradle configurations: You update/replace the dependency notation, the plugin adds the corresponding `versions.properties`.
- Unused version entry meta comment in the `versions.properties` file

**Comment by elect86** [comment]
I definitely agree, one single command to update all hardcoded deps for all the projects/modules

**Comment by jmfayard** [comment]
@martinbonnin @elect86 
This is now available, the task `./gradlew refreshVersionsMigrate` takes care of the migration
See https://jmfayard.github.io/refreshVersions/migrate/
