### ISSUE TITLE
Are plugins version handled ? 

### ISSUE THREAD

**Issue by martinbonnin** [jmfayard/refreshVersions#170]
When running the `migrateToRefreshVersionsDependenciesConstants` task on my project, it didn't find any of the Gradle plugins (AGP, etc...).

On the other hand, the android-sample has some code to handle that: https://github.com/jmfayard/refreshVersions/blob/6d13915d454fa40c506325a62db0ea11b385eab1/sample-android/plugins.gradle.kts#L11

In my project, all the plugins are added to the classpath in the root `build.gradle.kts`:

```
plugins {
    id("com.android.application").version("_").apply(false)
    id("org.jetbrains.kotlin.jvm").version(Versions.kotlin).apply(false)
    id("org.jetbrains.kotlin.android").version(Versions.kotlin).apply(false)
}
```

Do I need to do something more to have `plugins.gradle.kts` generated ?

**Comment by LouisCAD** [comment]
The version placeholder cannot be used in the plugins DSL, but refreshVersions support not defining the version in it, and defining `plugin.the.id.of.the.plugin` in `versions.properties`.

Regarding the plugins that don't have a plugin marker like `com.android.application` and require a dependency in the `classpath` configuration of the `buildscript`, support is coming in #167 (with version placeholder, as for regular dependencies).

For AGP, we support defining the module automatically if you don't specify the version of any of AGP plugin ids and have `plugin.android` defined in `versions.properties`.

**Comment by jmfayard** [comment]
It's handled in version 0.10.0 to be released soon
