### ISSUE TITLE
Setup development versions with bintray repository, and streamline release process

### ISSUE THREAD

**Issue by LouisCAD** [jmfayard/refreshVersions#174]
This will make dogfooding easier, and allow us to decouple releases from testing.

For the release process streamlining, I plan to take a semi-automatic approach like used in Splitties (where a Kotlin user/dev interactive script guides through each step, and saves progress in a text file until completion in case of crash/abort to resume after fix).

**Comment by jmfayard** [comment]
bintray is dead
