### ISSUE TITLE
Redirects not followed while getting maven metadata

### ISSUE THREAD

**Issue by martinbonnin** [jmfayard/refreshVersions#183]
Sadly, I cannot reproduce this problem anymore but this happened with Appboy SDK a few hours after they released 7.0.0

```
repositories {
        maven { url = uri("http://appboy.github.io/appboy-android-sdk/sdk") }
}

dependencies {
       implementation("com.appboy:android-sdk-ui-jetified:_")
}
```

This generated a malformed versions.properties:

```
version.com.appboy..android-sdk-ui-jetified=[some xml data here]
```

Unfortunately I cannot reproduce but it looked like an unhandled redirect, which would make sense considering there's little chance URL.readText() will follow redirects: https://github.com/jmfayard/refreshVersions/blob/502c47e7cb9394e813030b644ef7f299b430733f/refreshVersions/src/main/kotlin/de/fayard/versions/internal/LatestVersionsRetrieval.kt#L64

**Comment by LouisCAD** [comment]
I expect this to be fixed once we use OkHttp (that is the "cancellable network I/O" I had in mind while writing the TODO comment).

**Comment by LouisCAD** [comment]
We switched to OkHttp a while ago, so this issue should be fixed now.
