### ISSUE TITLE
Question: How to get a Version string manually

### ISSUE THREAD

**Issue by miikeat** [jmfayard/refreshVersions#184]
I would like to use refreshVersions to set the ktlint version in the ktlint-gradle-plugin:

```
ktlint {
    version.set("0.36.0") // "_" is not accepted here
    ...
}
```
Is there some refreshVersions mechanism to pull the Version and use it here or is it ok to use something like ```project.properties[...]``` 
```
ktlint {
    val ktlintVersion = project.properties["com.pinterest:ktlint:_"]
    version.set("$ktlintVersion")
    ...
}
```
The problem with that is that ```refreshVersions``` Task removes that version every time it's ran. 

Would be nice to know how to handle the not so ordinary cases of dependencies!

Other than that, Greate Plugin!!! It really cleaned up our Project a lot!

**Comment by vladimirfx** [comment]
Analogical use cases:
 - Vaadin version for (any) Vaadin plugin
 - versions for replace by processResouces task in some sort of deployment descriptors ( OSGI/Docker etc)

**Comment by NikkyAI** [comment]
this is probably going to break but currently works:

```
import de.fayard.versions.internal.InternalRefreshVersionsApi
import de.fayard.versions.internal.getVersionProperties

@UseExperimental(InternalRefreshVersionsApi::class)
val versionsMap =  getVersionProperties()
versionsMap.forEach { (key, value) ->
    logger.lifecycle("$key : $value")
}
```

for this to work there needs to be some dependency on what you want to grab though.. otherwise `refreshDependencies` task will wipe it
maybe you can define a new configuration to gradle that does nothing

@miikeat for you that this code should do the trick:

```kotlin
import de.fayard.versions.internal.InternalRefreshVersionsApi
import de.fayard.versions.internal.getVersionProperties

configurations {
    create("fake")
}

dependencies {
  add("fake", "com.pinterest:ktlint:_")
}

@UseExperimental(InternalRefreshVersionsApi::class)
val versionsMap =  getVersionProperties()

logger.lifecycle("ktlint: ${versionsMap["version.com.pinterest..ktlint"]}")
```

PS for a nicer key (`version.ktlint`).. use this rule:

```
com.pinterest:ktlint:*
              ^^^^^^
```

could refreshVersions register a no-op configuration automatically?

could this be exposed via a extension ? then it would be possible to call `refreshVersions.getVersion("version.jooq")` for example

**Comment by miikeat** [comment]
@NikkyAI Thanks! That looks great!

How can I add a custom rules? That would be handy for couple of other dependencies too!

**Comment by vladimirfx** [comment]
@NikkyAI Thanks

@jmfayard It would be nice to have Public API for that.

**Comment by LouisCAD** [comment]
Having a public API for that: I appended it to my priority list here: https://github.com/jmfayard/refreshVersions/projects/4#card-38206665

I hope I'll get the time to do it this year.

Thanks @NikkyAI for helping other users!

**Comment by LouisCAD** [comment]
Hello, the version 0.10.0 added the `versionFor` function. I hope you like it!
