### ISSUE TITLE
loosing dependencies with 0.7.0

### ISSUE THREAD

**Issue by nkiesel** [jmfayard/refreshVersions#185]
Hi,

We are still using `buildSrcVersions` because we started with that and also have nit yet upgraded to Gradle 6.  Thus, this report is for version 0.7.0.

We have a multi-module project with a mixture of Java and Kotlin modules.  Most dependencies are used by both but we now have one dependency that is only used by a Kotlin module.  We manually added that dependency to Libs.kt and Versions.kt. Running `gradle buildSrcVersions` will remove this dependency (and thus breaks the build).

Concrete setup:

 - `Libs.kt` contains `const val mock_web_server: String = "com.squareup.okhttp3:mockwebserver:" + Versions.mock_web_server`
 - `Versions.kt` contains `const val mock_web_server: String = "4.4.1"`
 - `modules/api/rest-client/build.gradle` contains `testImplementation Libs.mock_web_server`
 - `settings.gradle` contains `include "modules:api:rest-client"`
 
Any idea what is going wrong here?  I currently manually add the dependency back after each `buildSrcVersions` run, but that is obviously tedious.

**Comment by LouisCAD** [comment]
Hi, we are no longer working on `buildSrcVersions` and I'm not familiar with it personally.

That said, here's what I observed:
The constant name you have doesn't reflect the maven coordinates like I believe `buildSrcVersions` requires.
You are trying to do it manually while `buildSrcVersions` has a built-in mechanism to detect dependencies not yet managed. Please see the legacy documentation: https://github.com/jmfayard/refreshVersions/issues/88 under the "Replace your dependencies" heading.

**Comment by nkiesel** [comment]
I thought the new approach still does not work for multi-module setups, or did I misunderstand?

The tip about the constant name was spot on: I replaced the name with it's value in build.gradle, ran `buildSrcVersions` again (which picked a different name than the one we manually picked), and then replaced the value with the modified name.  Now everything is back in order. Thanks!

**Comment by LouisCAD** [comment]
Glad it worked for you!

`refreshVersions` and `dependencies` work perfectly for multi-module setups. There's only one limitation, that it shares with `buildSrcVersions`: it doesn't support having different versions for different modules.

**Comment by nkiesel** [comment]
Hmm, I should try that then.  Is there anything special to know for upgrading from 0.7.0?

**Comment by LouisCAD** [comment]
Apart from the current README, refreshVersions and dependencies are working, but have room for improvement, especially when it comes to the migration task. You can already use it, or you can wait for it to be improved.
