### ISSUE TITLE
extraArtifactVersionKeyRules are ignored when refreshVersions is run

### ISSUE THREAD

**Issue by LouisCAD** [jmfayard/refreshVersions#189]

**Comment by DanySK** [comment]
Hi, can you clarify what does that mean?
Does it imply that grouping is currently not working?

**Comment by LouisCAD** [comment]
Kinda yes, it implies custom artifact version key rules (what you call grouping) are ignored in the `./refreshVersions` task, and that bug makes it unusable, so I need to fix it.

**Comment by DanySK** [comment]
understood. Looking forward to it getting fixed then.

**Comment by LouisCAD** [comment]
I've not been able to reproduce it in the kotlin sample. It might be an issue when `buildSrc` is involved.
I'll try again in the project where I witnessed this issue later, and I'll consider having a sample that uses `refreshVersions` in `buildSrc`.

**Comment by DanySK** [comment]
I'm trying custom aliases in a project using `buildSrc` kotlin files, and it seems to be working as intended.
https://github.com/AlchemistSimulator/Alchemist/commit/414c2b86570e3a936683964d16923593f082fe05

**Comment by LouisCAD** [comment]
Finally found the culprit!
To use refreshVersions in the dependencies of a project, including in buildSrc, you need to bootstrap refreshVersions in the Gradle settings of the root project, but also the Gradle settings of the buildSrc.

The issue is that I was specifying extraArtifactVersionKeyRules for the root project, but not for buildSrc, which made that latter one overwrite it back to default rules since buildSrc settings are run after the settings of the root project (Gradle 6+, as required by refreshVersions).

I'm closing this issue in favor of #196.
