### ISSUE TITLE
Allow empty-matching in custom version alias rules

### ISSUE THREAD

**Issue by DanySK** [jmfayard/refreshVersions#195]
Consider the following dependencies in the `version.properties` file:

```
version.org.antlr..antlr4=4.8-1

version.org.antlr..antlr4-runtime=4.8-1
```

It'd be nice to group them under key `version.antlr4`, so as not to generate confusion in case multiple antlr versions are used in different subprojects.

Now however, I could not find any way to write a correct rule to obtain this behaviour, here are my attempts:

```
org.antlr:*
          ^
```
produces:
```
version.antlr4=4.8-1

version.antlr4-runtime=4.8-1
```

while rule:
```
org.antlr:antlr4*
          ^^^^^^
```
produces:
```
version.antlr4=4.8-1

version.org.antlr..antlr4=4.8-1
```
 
**Describe the solution you'd like**

Well, one generic suggestion I have is to reconsider regular expressions as a "companion language" for the current one. I've seen the @LouisCAD presentation where sie explains why a simpler language was picked, but as with any new language, there are potential issues once it gets to be used my many people, as refreshVersions deserves to be.

As an improvement to the current language, I believe we need a way to specify that some further dependency component could be existent or not. The current `*` operator has somewhat the same behaviour of the `+` regex operator, requires one or more chars.
If a disruption could be acceptable, by proposal would be to replace `*` with `+` (same behaviour), and reuse `*` as a matcher for 0 or more chars. This would make this rule:
```
org.antlr:antlr4*
          ^^^^^^
```
produce the intended
```
version.antlr4=4.8-1
```
alone, and the former behaviour could still be obtained by:
```
org.antlr:antlr4+
          ^^^^^^
```

A non-disruptive alternative would be to switch the proposed use of the `*` and `+` symbols, but that would be counterintuitive.

A final non-disruptive alternative would be to use a different symbol for the new "match also empty" operator, such as `!`.

**Comment by LouisCAD** [comment]
The limitations of the syntax are intentional so it works only for the naming conventions adopted for maven artifacts.

What you want is to suffix the matcher with `(-*)`, to indicate an optional ending that starts with a dash.

An example is here, with others in the parent directory: https://github.com/jmfayard/refreshVersions/blob/e8bfe5a90ef17103bd797b2e0a3848cfee3aa8a9/dependencies/src/main/resources/refreshVersions-rules/kotlin(x)-version-alias-rules.txt

**Comment by DanySK** [comment]
Thank you for the pointer. I can confirm that
```
org.antlr:antlr4(-*)
          ^^^^^^
```
Works indeed as intended.
