### ISSUE TITLE
Some version alias rules cause the insertion of a space in versions.properties

### ISSUE THREAD

**Issue by DanySK** [jmfayard/refreshVersions#200]
**Describe the bug**

As per subject, sometimes the rule interpreter outputs:

` version.packagename` (with a leading whitespace) rather than the expected `version.packagename` (with no leading space)

**To Reproduce**

Use the following custom rule:

```
com.uchuhimo:konf(-*)
             ^^^^
```

Apply the following dependencies:
```
dependencies {
    implementation("com.uchuhimo:konf:_")
    implementation("com.uchuhimo:konf-yaml:_")
}
```

Run `./gradlew refreshV` and observe `versions.properties`.

**Expected behavior**

As per any package, there is no space before `version.`

Any change to the rule I've tested works normally:

```
com.uchuhimo:konf(-*)
   ^         ^^^^
```
produces `version..konf`

```
com.uchuhimo:konf(-*)
            ^^^^^
```
produces `version:konf`, and so on.

I thought it could be related to selecting the initial part of the artifact name as custom key, but the same approach works flawlessly for a number of other packages:

```
com.github.cb372:scalacache(-*)
                 ^^^^^^^^^^

org.antlr:antlr4(-*)
          ^^^^^^

org.junit.jupiter:junit-jupiter(-*)
                  ^^^^^^^^^^^^^
```

They work. I'm puzzled.

**Comment by LouisCAD** [comment]
You are missing the "Actual behavior" part. That said, I think you're referring to the intentional leading whitespace that is there when the version key is too short. It's there to keep the `# available` comments aligned for easy upgrade.

**Comment by DanySK** [comment]
I see. I did not know of this behaviour. So, the minimum alias length is 6 chars. Good to know.

**Comment by LouisCAD** [comment]
Nope, the alias can be shorter, the spaces are not an issue (or did you witness otherwise?).

**Comment by DanySK** [comment]
Not for refreshVersions I'd say.
It's an issue for the current version of [UpGradle](https://github.com/DanySK/upgradle), but if you can reassure me that this behavior is to stay, I can support it easily.

**Comment by LouisCAD** [comment]
I wrote the rationale above:
https://github.com/jmfayard/refreshVersions/issues/200#issuecomment-651403722
so I don't see why this would change.

**Comment by DanySK** [comment]
Great. Adding support to UpGradle, then.
