### ISSUE TITLE
Improve hint for hardcoded dependencies versions

### ISSUE THREAD

**Issue by jschneider** [jmfayard/refreshVersions#210]
refreshVersions returns this output:

```
Found 4 hardcoded dependencies versions.

[org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.4-M3-release-207, org.jetbrains.kotlin:kotlin-serialization:1.4-M3-release-207, org.jetbrains.kotlin:kotlin-serialization-unshaded:1.4-M3-release-207]...
```

I have no idea where these dependencies are configured.
I think it would be helpful to provide a complete list of hardcoded dependencies versions including the files / projects they are configured in. 

E.g.:

Harcoded dependencies versions:

projectA: 
 - org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.4-M3-release-207
 -secondDep....:1.2.3

projectB: 
 - org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.4-M3-release-207
 -secondDep....:1.2.3

**Comment by LouisCAD** [comment]
That's an area that needs improvement, I agree. For now, you have the migration task that can help you walk the supposedly hardcoded dependency versions (there's some false positives that can be introduced by gradle plugins that we need to filter out).

**Comment by jmfayard** [comment]
Note to self: steal code from `migrateToAndroidX` 
https://github.com/LouisCAD/Splitties/blob/develop/plugin/src/main/kotlin/com/louiscad/splitties/MigrateAndroidxTask.kt#L97-L102

**Comment by jmfayard** [comment]
@jschneider We now have the task `./gradlew refreshVersionsMigrate` that detects and fix hardcoded versions

https://jmfayard.github.io/refreshVersions/migrate/
