### ISSUE TITLE
Merge dokka version management in version.kotlin

### ISSUE THREAD

**Issue by DanySK** [jmfayard/refreshVersions#211]
refreshVersions comes in with a handy custom rule for kotlin, which produces a `version.kotlin` entry. Starting with Kotlin 1.4.0-rc, though, dokka artifacts are sharing the kotlin version as well, namely, one should manually write stuff like:

```
version.org.jetbrains.dokka..dokka-core=version.kotlin

version.org.jetbrains.dokka..dokka-gradle-plugin=version.kotlin

version.org.jetbrains.dokka..javadoc-plugin=version.kotlin
```

I was wondering if it'd be possible to perform the bound automatically. Also (but I think there is another issue opened about it), when running `refreshVersions` on a project configured as such, `version.properties` gets broken due to duplicated entries:

```
version.org.jetbrains.dokka..dokka-core=1.4.0-rc

version.org.jetbrains.dokka..dokka-core=version.kotlin

version.org.jetbrains.dokka..dokka-gradle-plugin=1.4.0-rc

version.org.jetbrains.dokka..dokka-gradle-plugin=version.kotlin

version.org.jetbrains.dokka..javadoc-plugin=1.4.0-rc

version.org.jetbrains.dokka..javadoc-plugin=version.kotlin

```

**Comment by jmfayard** [comment]
That's a use case for `versionFor`
https://jmfayard.github.io/refreshVersions/add-dependencies/#get-the-version-from-anywhere

**Comment by LouisCAD** [comment]
@jmfayard I don't think so, it has nothing to do with to me. 🧐

Inferring matching version histories would still be interesting, though it's though because of the risk of false positives.

**Comment by jmfayard** [comment]
If versionFor is not an option, it could be done with a simpler api for rule 
https://github.com/jmfayard/refreshVersions/issues/580#issuecomment-1246244051

Then it's only a one liner

```properties
version.dooka=version.kotlin
```

> I was wondering if it'd be possible to perform the bound automatically

Actually this is something I had in mind for #580
