### ISSUE TITLE
version.properties not persisted

### ISSUE THREAD

**Issue by realdadfish** [jmfayard/refreshVersions#214]
I'm playing around with the task `migrateToRefreshVersionsDependenciesConstants` and figure if I exit the command loop after I replaced only a few versions, my `version.properties` file is emptied. I can only see versions popping up there while I'm in the command loop.

Is this desired behaviour? If so, why?

**Comment by realdadfish** [comment]
Also, on a totally unrelated note, I've read that you want to concentrate on refreshVersions and skip the support for buildSrc for now. Is there any helper / tool for now to extract the things from `versions.properties` in `buildscript` blocks of the main project module? Because there are a couple of dependencies I have that share a common version between runtime dependencies (managed by this plugin) and regular Gradle plugins.

**Comment by LouisCAD** [comment]
Which version are you using?

**Comment by realdadfish** [comment]
0.5.8

**Comment by WhosNickDoglio** [comment]
I'm using the latest version (0.9.7) and also seeing the issue with version.properties not being persisted. 

While the task is executing I can see the file updating but once I hit exit everything added gets removed.

**Comment by jmfayard** [comment]
That task is replaced by `refreshVersionsMigrate`
https://jmfayard.github.io/refreshVersions/migrate/
