### ISSUE TITLE
0.9.5-dev-009: Intermediate version output

### ISSUE THREAD

**Issue by realdadfish** [jmfayard/refreshVersions#220]
While testing the dev version I noticed that many in-between versions are now outputted compared to earlier versions of the plugin, i.e.

```
version.org.mockito..mockito-android=3.1.0
##                       # available=3.2.0
##                       # available=3.2.4
##                       # available=3.3.0
##                       # available=3.3.1
##                       # available=3.3.3
##                       # available=3.4.0
##                       # available=3.4.2
##                       # available=3.4.3
##                       # available=3.4.4
##                       # available=3.4.6
##                       # available=3.5.0
##                       # available=3.5.2
```

is printed, while I'd have expected only a single

```
version.org.mockito..mockito-android=3.1.0
##                       # available=3.5.2
```

Is this on purpose? This is not restricted to stable versions:

```
version.org.slf4j..log4j-over-slf4j=1.7.25
##                      # available=1.7.26
##                      # available=1.7.27
##                      # available=1.7.28
##                      # available=1.7.29
##                      # available=1.7.30
##                      # available=1.8.0-alpha0
##                      # available=1.8.0-alpha1
##                      # available=1.8.0-alpha2
##                      # available=1.8.0-beta0
##                      # available=1.8.0-beta1
##                      # available=1.8.0-beta2
##                      # available=1.8.0-beta4
##                      # available=2.0.0-alpha0
##                      # available=2.0.0-alpha1
```

**Comment by LouisCAD** [comment]
Yes, it's on purpose. It allows you to upgrade to newer but non latest versions with ease, handy when an API evolved incrementally, providing migration facilities that might have been removed in latest versions.

It also enables you to visualize at a glance how much "behind" your project is.

**Comment by realdadfish** [comment]
I'd still love to have some filtering there. People might not be interested in every alpha / beta version upstream provides, this spams the file quite a bit. For kotlintest for example roughly 40 subsequent snapshot versions are printed, all of which I'm not interested.

**Comment by LouisCAD** [comment]
I've been thinking about wrapping intermediate version with a region so the IDE can fold them.
What are your thoughts regarding that idea?

**Comment by realdadfish** [comment]
Well, won't make much of a difference. Imagine you're on the latest stable version, but the plugin still happily shows you dozens of snapshot and alpha versions, that then also pop up in code reviews (where you can't fold them away).

So personally no hard feelings, if you want to keep the complete output, keep it verbatim as-is. 

Am 19. August 2020 16:58:23 MESZ schrieb Louis CAD <notifications@github.com>:
>I've been thinking about wrapping intermediate version with a region so
>the IDE can fold them.
>What are your thoughts regarding that idea?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jmfayard/refreshVersions/issues/220#issuecomment-676478723

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
