### ISSUE TITLE
0.9.5-dev-009: SNAPSHOT version output and "silent" version.properties updates 

### ISSUE THREAD

**Issue by realdadfish** [jmfayard/refreshVersions#221]
While testing this version (and possibly earlier ones) I noticed that SNAPSHOT versions are printed as version proposals as well, like here:

```
version.org.xerial..sqlite-jdbc=3.32.3.2
##                  # available=3.32.3.3-SNAPSHOT
##                  # available=3.32.4-SNAPSHOT
```

Personally I'd love if the plugin would allow the configuration to suppress these special versions (maybe even other suffixed versions, like "*-alpha"), so users in a bigger dev team are not tricked into thinking that these are valid update targets. Eventually this can be solved somehow together with #192.

In general, while it is super-cool for the most part that the plugin automatically refreshes the contents of versions.properties, it could easily lead to git commit / PR spam, because users might accidentally commit the changed file without knowing it. Therefor it would be also super-cool if the plugin would gain a knob where these silent updates would not happen and only the explicit call to `refreshVersions` would touch `versions.properties` (except when adding new dependencies).

**Comment by LouisCAD** [comment]
> only the explicit call to `refreshVersions` would touch `versions.properties` (except when adding new dependencies).

That's already the current behavior.

Otherwise, yes, it's planned for #192

**Comment by jmfayard** [comment]
that's `rejectVersionIf { }`
https://jmfayard.github.io/refreshVersions/update-dependencies/#filter-which-versions-are-added-to-versionsproperties
