### ISSUE TITLE
v0.9.5 no longer automatically loads the latest version, is this wanted?

### ISSUE THREAD

**Issue by DanySK** [jmfayard/refreshVersions#227]
I noticed that, in case a version is unspecified in the `version.properties` file, refreshVersions 0.9.5 does not bind it to the latest it can, but fails with a message like:
```
        * What went wrong:
        Execution failed for task ':refreshVersions'.
        > Couldn't resolve version for ModuleId(group=com.github.kittinunf.fuel, name=fuel-coroutines)
```
I used this auto-select-latest feature to manually migrate up to date stuff quickly, was it dropped purposefully?
It can make it a little harder to migrate, especially when there are unknown custom version key rules, or when they change.

**Comment by DanySK** [comment]
It is strange because you can provide it with a non-existent version, and as far as the entry is correctly entered the system works as intended :open_mouth:

**Comment by DanySK** [comment]
To reproduce:

`settings.gradle.kts`
```kotlin
import de.fayard.refreshVersions.bootstrapRefreshVersions

buildscript {
    repositories { gradlePluginPortal() }
    dependencies {
        classpath("de.fayard.refreshVersions:refreshVersions:0.9.5")
    }
}
bootstrapRefreshVersions()
```

`build.gradle.kts`
```kotlin
plugins {
    `java-library`
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.scala-lang:scala-compiler:_")
}
```

This build fails, while adding

`versions.properties`
```java
version.org.scala-lang..scala-compiler=foo
```

Makes the build work. I believe it is a bug, or at least looks like that from an user perspective.

**Comment by LouisCAD** [comment]
I think it's a bug/regression. I'll take a look later.

**Comment by jmfayard** [comment]
Major bug that I can reproduce all the time, should be fixed with https://github.com/jmfayard/refreshVersions/pull/232

**Comment by DanySK** [comment]
@jmfayard before merging maybe it'd make sense to add a regression test, this looks quite a delicate feature not to have covered

**Comment by jmfayard** [comment]
I agree, best would be to add integratino tests based on **gradle testKit**
https://github.com/jmfayard/refreshVersions/issues/59

**Comment by DanySK** [comment]
I was about to write a library to simplify writing such tests, based on of the testing I've done for [this project](https://github.com/DanySK/gradle-latex/). Feel free to copy, there's few lines in the `build.gradle.kts`, an executor that fetches the available tests (`Tests.kt`), and one descriptor per test in yaml format. I know @LouisCAD doesn't tolerate yaml, but it's trivial to use TOML or Json instead without any change to the logic (it's based on the excellent [Konf](https://github.com/uchuhimo/konf) library).

Feel free to copy... I won't be able to isolate it to a nice library before the end of the year :disappointed:

**Comment by LouisCAD** [comment]
I found the culprit: it's in Gradle and appeared when I added support for authenticated repos.
I reported that bug and I'll do what I can to have it fixed in Gradle 6.7 so we can kiss this issue goodbye: https://github.com/gradle/gradle/issues/14694

**Comment by DanySK** [comment]
Thanks, that's been some hard digging I see

**Comment by LouisCAD** [comment]
Also, the workaround works on Gradle 6.4 and 6.5 but not 6.6, I need to dig in 6.6 internals too 😓

**Comment by jmfayard** [comment]
We definitely need to have integration test with gradleTestKit() so that we can test this kind of stuff with different versions of Gradle. 

Pablisco has quite good gradleTestKit tests in https://github.com/pablisco/auto-module
We could steal stuff from him
