### ISSUE TITLE
Support Gradle configuration cache

### ISSUE THREAD

**Issue by LouisCAD** [jmfayard/refreshVersions#228]
Relevant documentation: https://docs.gradle.org/nightly/userguide/configuration_cache.html

**Comment by julioz** [comment]
Hi, we're exploring configuration caching at SC; is this something you have planned on working soon, have an estimate you could provide, or a description of what prevents this work from happening?

**Comment by LouisCAD** [comment]
Hello, sorry for the late response.

I can't give any promises, but I hope we can address this issue in 2021.

**Comment by yogurtearl** [comment]
Also, you should make sure to test config cache with every task that the plugin has. 

E.g. `:refreshVersionsMigrate` has these config cache issues: 

`Invocation of 'Task.project' by task ':refreshVersionsMigrate' at execution time is unsupported.`
Have to grap the needed values during configuration and pass them in as `@Input` 

here:
https://github.com/jmfayard/refreshVersions/blob/873210a27849ad252af8d561d042d8730d23190e/plugins/dependencies/src/main/kotlin/de/fayard/refreshVersions/RefreshVersionsMigrateTask.kt#L16

and here:
https://github.com/jmfayard/refreshVersions/blob/873210a27849ad252af8d561d042d8730d23190e/plugins/dependencies/src/main/kotlin/de/fayard/refreshVersions/RefreshVersionsMigrateTask.kt#L24

Ideally this would be calculated at configuration time and passed an `@Input` to the task:
https://github.com/jmfayard/refreshVersions/blob/873210a27849ad252af8d561d042d8730d23190e/plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/MissingVersionEntries.kt#L51-L65

**Comment by LouisCAD** [comment]
Hello, FYI, I'm working on this issue right now, and I expect it to take a few days to complete.

If one of you want to join in a pair-programming session, let me know, I'll be happy to have one of you onboard!

**Comment by LouisCAD** [comment]
Thanks @pikzen for demonstrating it to work.
I checked the doc, tried something similar, did some testing, and it works well so long you don't try to run the `refreshVersions` task with configuration cache enabled. That's already a big improvement as it no longer prevents you from using configuration cache in the build.

I'll see if I can quickly handle the issue affecting the `refreshVersions` task before the impending release.

**Comment by LouisCAD** [comment]
It's impossible (and pointless) to support Gradle configuration cache for the `refreshVersions` task (see why [in the description here](https://github.com/jmfayard/refreshVersions/pull/495#issue-1112000624)), so I'm dropping this part.

The main goal is to allow projects to take advantage of configuration cache safely, and this has been implemented successfully.
