### ISSUE TITLE
Support custom versions.properties file path?

### ISSUE THREAD

**Issue by oh-Rin** [jmfayard/refreshVersions#239]
For multiple projects, it is better to use a version.properties file together, which can reduce the time it takes to repeatedly update dependencies when switching projects.

So, is it possible to add a gradle extension with a custom path?

**Comment by jmfayard** [comment]
Hello @oh-Rin 
this is something I support, but the use cases and the details would have to be fleshed out, and in any case this will wait that we do a proper release and that we have proper configuration support https://github.com/jmfayard/refreshVersions/issues/202

**Comment by oh-Rin** [comment]
> Hello @oh-Rin
> this is something I support, but the use cases and the details would have to be fleshed out, and in any case this will wait that we do a proper release and that we have proper configuration support #202

Okay, but this feature is very important to me, so is there any quick temporary solution?

**Comment by oh-Rin** [comment]
resolved! I defined the parameter:
```kotlin
 bootstrapRefreshVersions(versionsPropertiesFile = File("../../versions.properties"))
```

https://github.com/jmfayard/refreshVersions/blob/master/plugins/dependencies/src/main/kotlin/de/fayard/refreshVersions/RefreshVersionsSetup.kt#L42
