### ISSUE TITLE
buildSrc config not working

### ISSUE THREAD

**Issue by jschneider** [jmfayard/refreshVersions#243]
I tried to configure my buildSrc to also support refreshVersions.
I followed the documentation (at least I think I ded) but get this message:

``` You also need to bootstrap refreshVersions in the settings.gradle[.kts] file of the root project
> /home/johannes/projects/com.cedarsoft.monorepo/buildSrc/build/refreshVersions_versionsPropertiesFilePath.bin (No such file or directory)
``` 

The root project definately supports refreshVersions. I am using it for a while.

Version number: 0.9.5
Build scan (with not much more information:)
https://scans.gradle.com/s/4jqlh3ul3whhk

**Comment by LouisCAD** [comment]
Hello @jschneider , can you share a reproducing project for to look at, please?

**Comment by jschneider** [comment]
Hm. The problem no longer exists. 
I assume I did something wrong ;-)

--> Maybe you could add a line in the documentation that the buildSrc project uses the same "versions.properties"? And that it is not required/necessary to execute "gradle refreshVersions" in the buildSrc directory?
