### ISSUE TITLE
Do not automatically remove unused dependencies in the versions.properties file when update

### ISSUE THREAD

**Issue by RinOrz** [jmfayard/refreshVersions#244]
I don't want to delete unused dependency properties every time I update with `./gradlew refreshVersions`. Is there an API that can help me disable this feature?

**Comment by LouisCAD** [comment]
@oh-Rin There's no such API, but you can add a dummy configuration where you have the dependencies that would otherwise be removed as a workaround.

**Comment by oh-Rin** [comment]
> @oh-Rin There's no such API, but you can add a dummy configuration where you have the dependencies that would otherwise be removed as a workaround.

This may be a bit tricky, because I share a versions.properties for multiple different projects, so I don’t want to delete dependencies used by other projects when one of the projects is updated

**Comment by LouisCAD** [comment]
It's less tricky if you have a "master" project that has all the dependencies in a dummy configuration, that is the only project where you run `refreshVersions`.

**Comment by oh-Rin** [comment]
It is true, but I prefer refreshVersions to be used in all projects, which will undoubtedly be more convenient...Is this possible?


> It's less tricky if you have a "master" project that has all the dependencies in a dummy configuration, that is the only project where you run `refreshVersions`.

**Comment by oh-Rin** [comment]
The solution I currently think of is to record `versions.properties` and convert to `java.util.Properties` before updating

Then add the missing dependencies back after the update, but I encountered a problem, `java.util.Properties` can’t know "#available=***" of the dependency

In the end it looks like this:
![image](https://user-images.githubusercontent.com/58068445/92316879-6dd31a00-f02c-11ea-9df4-3e5b5af3d8d5.png)

**Comment by LouisCAD** [comment]
> It is true, but I prefer refreshVersions to be used in all projects, which will undoubtedly be more convenient...Is this possible?

Are you using Gradle's includedBuilds (aka. composite builds)?

**Comment by oh-Rin** [comment]
> > It is true, but I prefer refreshVersions to be used in all projects, which will undoubtedly be more convenient...Is this possible?
> 
> Are you using Gradle's includedBuilds (aka. composite builds)?

No, for some special reasons, I can’t use composite builds, because some projects I work with others, but we all want to use the same dependencies... well the situation is a bit complicated

**Comment by oh-Rin** [comment]
Ok, I’m very lucky, I solved this problem in a simple way, now i can work.

![image](https://user-images.githubusercontent.com/58068445/92317151-349ca900-f030-11ea-8ce8-5778eb0b6f25.png)

![image](https://user-images.githubusercontent.com/58068445/92317133-0d45dc00-f030-11ea-8776-83793c436afc.png)


My situation should be special, this question can be closed now

**Comment by LouisCAD** [comment]
Would be best to post an actual snippet rather than a screenshot for other to copy paste the relevant parts if they have the same use case since you might not be the only one ever having such a use case.

**Comment by oh-Rin** [comment]
Thanks for your suggestion, but I am not sure if my solution is correct or other problems, this is my code snippet for `build.gradle.kts`:

```kts
object VersionsProperties {
  val file = File(rootDir, "versions.properties") // or in other custom locations
  var last = current
  val current get() = file.readLines()
}

tasks.findByPath(":refreshVersions")?.apply {
  doFirst {
    VersionsProperties.last = VersionsProperties.current
  }
  doLast {
    val old = VersionsProperties.last
    val new = VersionsProperties.current.toMutableList()
    var locked = true
    // 通过对比找出新的 versions.properties 文件中被删除的依赖
    old.forEach { line ->
      // 如果到达了下一个依赖组
      if (!line.startsWith("#") && line.contains("=")) {
        // 代表后面的行不能够记录了
        locked = true
      }
      // 如果依赖组丢失则记录，并且开锁
      if (!new.contains(line)) {
        new.add("\n" + line)
        // 代表依赖组后面的 "available" 数据可以被记录
        locked = false
      }
      // 允许记录当前依赖组的 "available" 数据
      if (!locked && line.contains("# available=")) new.add(line)
    }
    // 更新依赖文件
    VersionsProperties.file.writeText(new.joinToString("\n"))
    VersionsProperties.last = new
  }
}
```

**Comment by LouisCAD** [comment]
In version 0.10.0, unused version keys are not removed. We plan to add an informative metadata comment when unused in a future release.
