### ISSUE TITLE
Task 'migrateToRefreshVersionsDependenciesConstants' not found in root project 'xxx_Android'.

### ISSUE THREAD

**Issue by HLQ-Struggle** [jmfayard/refreshVersions#247]
Hello, I’m a newbie to Android, and I saw your articles and libraries while doing gradle optimization.

When I follow the tutorial instructions to integrate, it always prompts the following error:

 ```
✘ heliquan@Mac  ~/CodePro/AndroidStudioPro/xxx_Android   master ●✚  ./gradlew migrateToRefreshVersionsDependenciesConstants --console=plain


FAILURE: Build failed with an exception.

* What went wrong:
Task'migrateToRefreshVersionsDependenciesConstants' not found in root project'FingerAdvisor_Android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Sorry, I don’t know what caused this error.

Explain my steps. First, my project contains multiple modules (app, helper, weight...):

- Create a settings.gradle.kts file in the root directory and copy the following code:

```
// settings.gradle.kts
import de.fayard.refreshVersions.bootstrapRefreshVersionsForBuildSrc

// Here you might have some pluginManagement block:
pluginManagement {
    //...
}

buildscript {
    repositories {gradlePluginPortal()}
    dependencies.classpath("de.fayard.refreshVersions:refreshVersions:0.9.5")
}

bootstrapRefreshVersionsForBuildSrc()
```

Then execute the following command in the Terminal of Android Studio:

- ./gradlew migrateToRefreshVersionsDependenciesConstants --console=plain

Finally came out this error exception.

Hope to get your guidance~

**Comment by LouisCAD** [comment]
Hi @HLQ-Struggle, why do you use the buildSrc specific bootstrap for the root project?

**Comment by HLQ-Struggle** [comment]
Hi @LouisCAD ,because my Android project is currently modularized and third-party dependencies are referenced in every module, it is troublesome to manage.

The direct buildSrc scheme was originally adopted, but this scheme cannot update the reference version.

**Comment by LouisCAD** [comment]
@HLQ-Struggle Okay, so this is a mistake. The buildSrc bootstrap is if you need to use refreshVersions for the dependencies of the `buildSrc` itself. In all cases, you need to use the regular bootstrap for the root project, so go check out the doc again 🙂 .

I'm assuming this is the issue you're encountering and that the solution I gave you will do. If you are still blocked, feel free to comment here or open another issue.

**Comment by HLQ-Struggle** [comment]
@LouisCAD ,regarding what you said "The buildSrc bootstrap is if you need to use refreshVersions for the dependencies of the buildSrc itself." I did add the corresponding dependencies in the root directory.

I read your document, but didn't find out what I should do better.

Hope to get your help, thank you~ 😭

**Comment by LouisCAD** [comment]
@HLQ-Struggle You need to read the setting up guide very carefully.

You can also take a look at the existing [sample-multi-modules](https://github.com/jmfayard/refreshVersions/tree/336ff36e6bcd27fc0333a958f620179dd6982015/sample-multi-modules) or at the unreleased [sample-android](https://github.com/jmfayard/refreshVersions/tree/bc0c00ca66c757d5616e6334eb94217229a70974/sample-android) and see how their configuration differs from your project (minus the hack we have to sync the version on a text file).

**Comment by HLQ-Struggle** [comment]
@LouisCAD ,Okay, now I will continue to look at the usage documentation. thank you very much

**Comment by LouisCAD** [comment]
@HLQ-Struggle You need to read [the setting up guide](https://github.com/jmfayard/refreshVersions/blob/master/docs/Setting-up.adoc) before the usage documentation.

In the snippet you posted, you had `bootstrapRefreshVersionsForBuildSrc()` but you need to replace it with `bootstrapRefreshVersions()`, as shown in the ["Bootstrap in root project" section](https://github.com/jmfayard/refreshVersions/blob/master/docs/Setting-up.adoc#bootstrap-in-root-project)

**Comment by HLQ-Struggle** [comment]
@LouisCAD Re-read the reference instructions you provided.

First of all, my Android project is currently divided into app, helper, weight and other modules, and then I create settings.build.kts, because the language of my project is Kotlin.

![image](https://user-images.githubusercontent.com/19400093/93051564-449f3300-f697-11ea-9f84-589ff3c97b03.png)

```
// settings.gradle.kts
import de.fayard.refreshVersions.bootstrapRefreshVersions

// Here you might have some pluginManagement block:
pluginManagement {
    //...
}

buildscript {
    repositories { gradlePluginPortal() }
    dependencies.classpath("de.fayard.refreshVersions:refreshVersions:0.9.5")
}

bootstrapRefreshVersions()
```

Then synchronize it and execute the following command:

`./gradlew migrateToRefreshVersionsDependenciesConstants --console=plain
`
The result is still the following exception:

```
➜  xxx_Android git:(master) ✗ ./gradlew migrateToRefreshVersionsDependenciesConstants --console=plain
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details


FAILURE: Build failed with an exception.

* What went wrong:
Task 'migrateToRefreshVersionsDependenciesConstants' not found in root project 'xxx_Android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
➜  xxx_Android git:(master) ✗ 
```

I read the reading guide repeatedly, but I still don't know where I have a problem. 😭

**Comment by LouisCAD** [comment]
@HLQ-Struggle You have both a `settings.gradle.kts` and a `settings.gradle`.
Pick one, use the correct bootstrap for the corresponding DSL language (Kotlin or Groovy), remove the other one, and voilà.

**Comment by HLQ-Struggle** [comment]
My steps are as follows:

Step 1: Upgrade gradle to 6.4.1

`./gradlew wrapper --gradle-version 6.4.1`

Step 2: Add plugins to settings.gradle

```
rootProject.name='FingerAdvisor_Android'
include':app'
include':helper'
include':weight'

// settings.gradle.kts
import de.fayard.refreshVersions.RefreshVersionsSetup

// Here you might have some pluginManagement block:
pluginManagement {
     //...
}

buildscript {
     repositories {gradlePluginPortal()}
     dependencies.classpath("de.fayard.refreshVersions:refreshVersions:0.9.5")
}

RefreshVersionsSetup.bootstrap(settings)
```

But the following exception is prompted:

![image](https://user-images.githubusercontent.com/19400093/93057974-4f5ec580-f6a1-11ea-9635-60145b5adfc6.png)

Excuse me, where is my operation error? 😭😭😭

**Comment by LouisCAD** [comment]
@HLQ-Struggle Please, don't copy paste all blindly and try to understand what you are doing.

The `pluginManagement` block is not needed as you can understand from the comment above:
```
// Here you might have some pluginManagement block:
pluginManagement {
     //...
}
```

Regardless of this oversight, you could just have read the error message that tells you the order of things is wrong.

Note that after removing that `pluginManagement` block, you'll also need to put the bootstrap above your existing code (includes, root project name…). Just like in the samples actually.

**Comment by HLQ-Struggle** [comment]
@LouisCAD When I execute the following command:

`./gradlew migrateToRefreshVersionsDependenciesConstants --console=plain
`
The prompt is as follows error:

```
➜  xxx_Android git:(master) ✗ ./gradlew migrateToRefreshVersionsDependenciesConstants --console=plain

> Task :migrateToRefreshVersionsDependenciesConstants
All the following modules have hardcoded dependencies versions

1. :app (24)
2. :helper (10)
3. :weight (9)
4. Exit

Type the number of the Gradle module you want to migrate first:
weight

> Task :migrateToRefreshVersionsDependenciesConstants FAILED
--> GET https://plugins.gradle.org/m2/de/fayard/refreshVersions/refreshVersions/maven-metadata.xml
<-- 200 OK https://plugins.gradle.org/m2/de/fayard/refreshVersions/refreshVersions/maven-metadata.xml (1091ms, unknown-length body)

> Task :refreshVersions
Found 59 hardcoded dependencies versions.

[com.android.tools.build:gradle:4.0.1, org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.71, com.android.tools.build:aapt2:4.0.1-6197926]...

To ensure single source of truth, refreshVersions only works with version placeholders,
that is the explicit way of marking the version is not there (but in the versions.properties file).

If you intentionally want to keep hardcoded versions so a module has a different version of a
dependency than the rest of the project, you can safely ignore this warning for these artifacts,
but keep in mind refreshVersions will not show available updates for these.

Note that a migration task is planned in a future version of refreshVersions.

See https://github.com/jmfayard/refreshVersions/issues/160

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':migrateToRefreshVersionsDependenciesConstants'.
> java.util.InputMismatchException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
2 actionable tasks: 2 executed
➜  FingerAdvisor_Android git:(master) ✗ 

```
At the same time, I checked according to the suggested issues, but no solution was found. How should I do this? Thank you

**Comment by LouisCAD** [comment]
I'll not read the instructions for you. Please be considerate of our time and figure it out, all the info is there.
