### ISSUE TITLE
Keys should be sorted in versions.properties

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#256]
**Is your feature request related to a problem? Please describe.**

In https://github.com/LouisCAD/kotlin-libraries-playground we have lots of people bringing pull requests, usually adding a dependency in `build.gradle.kts` AND a key in `versions.properties`

If I have to merge two pull requests, the second will systematically have a merge conflict

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/459464/94909524-94f1ff80-04a3-11eb-84af-2553e32e86e0.png">

**Using the samples**

Just have a look at the PRs at https://github.com/LouisCAD/kotlin-libraries-playground/pulls
 
**Describe the solution you'd like**

We should have a VersionPropertiesWriter or something that would make sure everything is written in a stable sorting order

**Comment by LouisCAD** [comment]
As a workaround, running the `refreshVersions` task will fix the order.
I plan to make a new parser and writer that resolves this problem.

**Comment by LouisCAD** [comment]
Done, and released in 0.10.0
