### ISSUE TITLE
We need to automate migration for added version key rules and added dependency notations

### ISSUE THREAD

**Issue by LouisCAD** [jmfayard/refreshVersions#259]
Ideally, the tests that already make sure we don't remove any dependency notation should also fail on additions, after generating migration resources to be picked up by migration code, and the tests would pass again after the migration resources add edited.

A manual edit would also be required to ensure just running the tests twice doesn't succeeds.

I think a pair-programming session with you @jmfayard would be great to tackle this issue with a great solution that helps us move faster and safer regarding bundling dependency notations.

Finally, we could also handle dependency notations removals and renames to be able to remove support for some of them if needed without breaking users badly.

**Comment by jmfayard** [comment]
done
