### ISSUE TITLE
Cannot fetch Gradle release-candidate

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#267]
I run `$ ./gradlew refreshVersions` from `kotlin-sample`

It failed with a stacktrace https://scans.gradle.com/s/n7h2qhp6cunaw/failure#1

Reason: `$ curl https://services.gradle.org/versions/release-candidate` returns an empty JSON instead of what was expected.

I asked why on the Gradle slack channel.

Suggestion: since we are targetting normal users, not Gradle geeks, 
I would say we only care about the current stable release of Gradle

```diff
    @Suppress("unused") // Entries used with values()
    enum class VersionType(val apiPath: String) {
        Release("current"),
-        ReleaseCandidate("release-candidate"),
-        ReleaseNightly("release-nightly"),
-        Nightly("nightly"),
-        All("all")
    }
```

**Comment by LouisCAD** [comment]
Thanks for noticing! Will be fixed in 0.9.7.
