### ISSUE TITLE
Firebase crashlytics Gradle plugin is accidentally included in BOM config

### ISSUE THREAD

**Issue by simonsickle** [jmfayard/refreshVersions#272]
**Checklist**

- [ ] I tried to reproduce the bug in my fork of the [Kotlin Libraries Playground](https://github.com/LouisCAD/kotlin-libraries-playground), or in one of the samples in this repository
- [ ] I have run with `$ ./gradlew --scan refreshVersions` to [provide a Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg)

**Describe the bug**

The `crashlyticsGradlePlugin` is a part of the BOM firebase config (which is set as default), however this causes the plugin to not be found, which blocks building. `performanceMonitoringGradlePlugin` and `appDistributionGradlePlugin` are not like this, and are simply constants outside of the firebase config.

**To Reproduce**

Build scan URL: https://scans.gradle.com/s/xxxxxxxxxx

1. Open build.gradle.kts for rootProject
2. Add `classpath(Firebase.crashlyticsGradlePlugin)` and notice no build
3. Add `classpath(Firebase.`no-BoM`.crashlyticsGradlePlugin)` and notice it builds 

**Expected behavior**

`crashlyticsGradlePlugin` should be a constant like the other plugins, so that gradle can build the app

**Additional context**

**Comment by LouisCAD** [comment]
You need to also depend on the Firebase BoM:
```
classpath(platform(Firebase.bom))
```
It needs to be in the `buildscript`.

**Comment by joharei** [comment]
@LouisCAD I've tried your suggestion, but it doesn't seem to work. Neither can I find any mention anywhere that suggests BoM works in the `buildscript`.

This is what I tried:
```kotlin
buildscript {
    repositories {
        // ...
    }
    dependencies {
        classpath(platform(Firebase.bom))
        classpath(Firebase.crashlyticsGradlePlugin)
    }
}
```

This fails with the message:
```
org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.google.firebase:firebase-crashlytics-gradle:.
```

Did I misunderstand, or do you have any other insight?

**Comment by LouisCAD** [comment]
I think it's been broken in recent versions of the BoM, I had the same issue recently @joharei
