### ISSUE TITLE
Special exclusions for well known versions of well known libraries

### ISSUE THREAD

**Issue by DanySK** [jmfayard/refreshVersions#292]
Currently refreshVersions proposes old versions of some software products as upgrades when they are actually downgrades.
The classic example is commons-io: latest version is 2.8.0, yet refreshVersions proposes 20030203.000550 as an upgrade.

I understand the logic behind that: who published the library used inconsistent versioning and refreshVersions is actually doing nothing wrong. This however plays badly with further automation, see e.g. https://github.com/Protelis/Protelis/pull/411.

I was wondering if it would make sense to create a list of artifacts/versions not to consider into updates.
I realize this is something hard to maintain, but I expect it not to be particularly big (Apache commons stuff, possibly Scala, not sure anything else).

What do you think?

**Comment by LouisCAD** [comment]
Hi Dany, it will take more time for us to get there, but we've laid the foundation to allow future metadata comments which will be able to control/filter the versions shown as available by refreshVersions later down the road.

Thanks for letting us know about that unfortunate real world example, it'll give food for thought when we design the details of these features.

**Comment by jmfayard** [comment]
Hello Dany, this will be doable when https://github.com/jmfayard/refreshVersions/pull/347 is merged and released

**Comment by DanySK** [comment]
Very nice! Thanks!
