### ISSUE TITLE
"Failed requirement." when running ./gradlew migrateToRefreshVersionsDependenciesConstants --console=plain

### ISSUE THREAD

**Issue by iainism** [jmfayard/refreshVersions#298]
**Checklist**

- [no] I tried to reproduce the bug in my fork of the [Kotlin Libraries Playground](https://github.com/LouisCAD/kotlin-libraries-playground), or in one of the samples in this repository
- [yes] I have run with `$ ./gradlew --scan refreshVersions` to [provide a Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg)

**Describe the bug**

In Android Studio 4.1.1 `./gradlew migrateToRefreshVersionsDependenciesConstants --console=plain` fails with a "Failed requirement"

The "Android" perspective then vanishes from the 'Project' pane.

**To Reproduce**

Build scan URL: https://scans.gradle.com/s/p7azbiftrzjwo

I have a `buildSrc` folder so I have used `bootstrapRefreshVersionsForBuildSrc()`

**Expected behavior**
Refresh versions runs without fatal error

**Comment by LouisCAD** [comment]
This is likely due to misconfiguration:

The boostrap for buildSrc should only be used for buildSrc, not for the host project.

FYI, the configuration will be simplified in the future, but in the meantime, please double check the setup guide.

**Comment by iainism** [comment]
Ah, whoops - that's embarrassing!

Thank you for the fast response :-)
