### ISSUE TITLE
In Android Studio IDE

### ISSUE THREAD

**Issue by ravenfeld** [jmfayard/refreshVersions#302]
import de.fayard.refreshVersions.RefreshVersionsSetup in settings.gralde is recognized as an error but there is no problem of compilation

All the dependencies that we write with "_" are in warning and we suggest to replace by the version

This is only the display the compilation works very well but here I wanted to put it back

**Comment by LouisCAD** [comment]
Here's how to tell lint to stop warning you: https://github.com/jmfayard/refreshVersions/issues/270#issuecomment-709602733
