### ISSUE TITLE
Gradle composite build 

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#31]
- Upgrade to Gradle 5.1 
- Use its composite build feature that now works for plugin
- Doc https://docs.gradle.org/5.1/userguide/composite_builds.html
- Samples https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/compositeBuilds

> Apply plugins from included build using plugins { } block
> The plugins { } block in build scripts can now be used to refer to plugins defined in included builds. In previous versions of Gradle, this was possible but required some additional boiler-plate code in the settings file. This boiler-plate is now no longer required.
> This change makes it super easy to add a test build for a Gradle plugin and streamlines the process of implementing a Gradle plugin. You can also use this feature to conveniently work on changes to a plugin and builds that use that plugin at the same time, to implement a plugin that is both published and used by projects in the same source repository, or to structure a complex build into a number of plugins.
> Using the plugins { } block also makes the Gradle Kotlin DSL much more convenient to use.
> You can find out more about composite builds in the user manual.

**Comment by jmfayard** [comment]
That's it, I have a composite build for my plugins. 

- Open in IntelliJ `composite/.build.gradle.kts`
- Run `checkAll` will run all unit tests *and* run `gradlew :buildSrcVersions` in the modules `sample-groovy` and `sample-kotlin`
- Any change made inside the `plugin` module will be instantly available to `sample-groovy`and `sample-kotlin` without any need to publish the plugin first

![image](https://user-images.githubusercontent.com/459464/50916890-91e7ed80-143c-11e9-95c2-51492dbf075b.png)

**Comment by LouisCAD** [comment]
Shouldn't this issue be closed?

**Comment by LouisCAD** [comment]
This issue seems obsolete, am I right?
