### ISSUE TITLE
Gradle plugin failed to add

### ISSUE THREAD

**Issue by RinOrz** [jmfayard/refreshVersions#310]
**Describe the bug**

> Plugin [id: 'symbol-processing', version: '1.4.20-dev-experimental-20201204', artifact: 'com.google.devtools.ksp:symbol-processing:null'] was not found in any of the following sources:
> 
> - Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/6.8-rc-1/userguide/standard_plugins.html for available core plugins)
> - Plugin Repositories (could not resolve plugin artifact 'com.google.devtools.ksp:symbol-processing:null')

**Additional context**

> settings.gradle.kts

```kotlin
pluginManagement {
  resolutionStrategy {
    eachPlugin {
      when (requested.id.id) {
        "symbol-processing" ->
          useModule("com.google.devtools.ksp:symbol-processing:${requested.version}")
      }
    }
  }
  ...
}
```

> build.gradle.kts

```kotlin
plugins {
  ...
  id("symbol-processing")
}
```

> versions.properties

```properties
plugin.symbol-processing=1.4.20-dev-experimental-20201204
```

**Comment by LouisCAD** [comment]
Hi, versions of `pluginManagement.resolutionStrategy` are not supported. You need to use the `buildscript.dependencies.classpath` way.

**Comment by RinOrz** [comment]
> Hi, versions of `pluginManagement.resolutionStrategy` are not supported. You need to use the `buildscript.dependencies.classpath` way.

`buildscript.dependencies.classpath` does not seem to support `_` placeholders?

**Comment by LouisCAD** [comment]
I don't know what you mean by "seem", but it's supported, like any other dependencies, except for Gradle settings files (because we need the egg before tbe chicken).

**Comment by RinOrz** [comment]
> I don't know what you mean by "seem", but it's supported, like any other dependency, except for Gradle settings files (because we need the egg before tbe chicken).

```kotlin
buildscript {
  repositories {
    gradlePluginPortal()
    jcenter()
    google()
  }

  dependencies.classpath("com.google.devtools.ksp:symbol-processing:_")
```

It doesn't work.

**Comment by NiccoMlt** [comment]
What is the right solution for this problem?
I tried the above approach, and I cannot make it work either.

For context, I'm modifying a [KVision template](https://github.com/rjaros/kvision-examples/tree/master/template-fullstack-ktor) to use refreshVersion and I'm trying to import [kvision-gradle-plugin](https://search.maven.org/artifact/io.kvision/kvision-gradle-plugin).

**Comment by LouisCAD** [comment]
@NiccoMlt Please, open a new issue, and specify how it fails for you.

**Comment by NiccoMlt** [comment]
Hi, I'm sorry, while I was preparing the issue following the template, I figured out what I was doing wrong.

I was both misplacing the `buildscript { repositories { } dependencies { } }` blocks and wrongly applying the plugin.

If you don't mind, I leave the working setup down here for future reference:

> build.gradle.kts
>
> ```kotlin
> buildscript {
>     repositories {
>         gradlePluginPortal()
>         mavenCentral()
>     }
>     dependencies {
>         classpath("io.kvision:kvision-gradle-plugin:_")
>     }
> }
> 
> [...]
> 
> apply(plugin = "kvision")
> 
> [...]
> ```
