### ISSUE TITLE
Ability to add grouping rules for other repos

### ISSUE THREAD

**Issue by tasomaniac** [jmfayard/refreshVersions#312]
**Is your feature request related to a problem? Please describe.**

This project has a really cool feature where you don't have to maintain multiple versions since a library group is known to use the same version for all of its artifacts. Good example is `retrofit2`. All of it's versions will be simply stored in `version.retrofit2` and be shared.
 
**Describe the solution you'd like**

The same applies to some of group of artifacts too. `refreshVersions` can provide rules functionality to support this. And `versions.properties` will become easier to maintain.

**Comment by moritzruth** [comment]
Another example: Netty

**Comment by LouisCAD** [comment]
This is already supported but not documented. You can see an example in the `sample-kotlin` sample.

FYI, we have been thinking of different approaches where this could partially be inferred, or where it could be defined from code, but both of these approaches seem tricky to implement.

**Comment by tasomaniac** [comment]
Is it possible to link to the example? I couldn't see how it is done. I just checked. It seems like the following version is defined 2 times back to back 
https://github.com/jmfayard/refreshVersions/blob/main/sample-kotlin/versions.properties#L84

**Comment by joharei** [comment]
> Is it possible to link to the example? I couldn't see how it is done. I just checked. It seems like the following version is defined 2 times back to back
> https://github.com/jmfayard/refreshVersions/blob/main/sample-kotlin/versions.properties#L84

@tasomaniac If you remove lines 84-86, the sample seems to work correctly, using the version from `version.apache.poi`. However, I'd expect the plugin to remove those duplicate lines by itself since they are covered by a shorter name. @LouisCAD Is this a bug, or is it intended?

**Comment by LouisCAD** [comment]
@joharei Probably a bug, though in future versions, we might have a different behavior as we might stop auto-removing unused entries, just adding a warning/info comment instead.

**Comment by jmfayard** [comment]
I've documented how it works here 

https://github.com/jmfayard/refreshVersions/issues/356#issuecomment-843276157
