### ISSUE TITLE
Some grouping rules are ignored

### ISSUE THREAD

**Issue by joharei** [jmfayard/refreshVersions#316]
**Checklist**

- [x] I tried to reproduce the bug in my fork of the [Kotlin Libraries Playground](https://github.com/LouisCAD/kotlin-libraries-playground), or in one of the samples in this repository
- [x] I have run with `$ ./gradlew --scan refreshVersions` to [provide a Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg)

I'm trying to add some grouping rules for a couple of androidx libraries, but it seems to me that they are ignored. Here's my rules file:
```
androidx.compose.*:*
^^^^^^^^^^^^^^^^

androidx.paging:paging-compose
^^^^^^^^^^^^^^^.       ^^^^^^^

com.google.dagger:hilt-compiler
    ^^^^^^^^^^^^^.^^^^
```
Note that the last entry with the `hilt-compiler` is working fine, which indicates to me that I've set this up correctly.
When I run gradle sync or refreshVersions, I get this in my `versions.properties`:
```
version.androidx.compose.foundation=1.0.0-alpha10

version.androidx.compose.material=1.0.0-alpha10

version.androidx.compose.runtime=1.0.0-alpha10

version.androidx.compose.ui=1.0.0-alpha10

version.androidx.paging=2.1.2
```
But I was expecting this:
```
version.androidx.compose=1.0.0-alpha10

version.androidx.paging=2.1.2

version.androidx.paging.compose=1.0.0-alpha05
```
Is there something wrong with my androidx rules, or do they conflict with the built-in ones maybe? Or have I misunderstood this feature completely? :sweat_smile:

**To Reproduce**

Build scan URL: https://gradle.com/s/czagnpn7nsgxo
(note that the scan shows an error, but it seems to run fine. Might be because I was running a local snapshot on the main branch, but the same behavior happens with the latest stable version.)

**Comment by joharei** [comment]
This issue impacts the `paging-compose` library mentioned above most seriously, and now I'm facing the same issue with the similar `navigation-compose`. This makes it impossible as far as I can see to use these libraries with refreshVersions, and I have to specify their versions manually:
```kotlin
implementation("androidx.paging:paging-compose:1.0.0-alpha05")
implementation("androidx.navigation:navigation-compose:1.0.0-alpha05")
```

**Comment by LouisCAD** [comment]
Version 0.10.0 is out with the fix!
In fact, all of the AndroidX dependency notations have been thoroughly reviewed and checked.

Note that there's not common compose version key rule because so far, I have no guarantee the different sub-families won't have different paces/versions at some point.
