### ISSUE TITLE
Defines lifecycle-viewmodel-compose version wrongly

### ISSUE THREAD

**Issue by KirillAmurskiy** [jmfayard/refreshVersions#322]
**Describe the bug**

When one adds `androidx.lifecycle:lifecycle-viewmodel-compose:_` dependency, refreshVersion sets the version from `lifecycle-*` (2.3.0) instead of compose specific one (1.0.0-alpha01). So nothing works after it and one has to set the version explicitly in the gradle file (the way how to specify version explicitly in versions.properties is not known).

Current versions of lifecycle's libs:
![image](https://user-images.githubusercontent.com/5471833/108831664-411bba80-75ec-11eb-94e1-3118dd372f55.png)

How the bug looks in Android studio:
![image](https://user-images.githubusercontent.com/5471833/108831921-9fe13400-75ec-11eb-9209-89cff1ba2bce.png)

**To Reproduce**

1. Get the last Android Studio 2020.3.1 Canary 7
2. Create Empty Compose Activity project
3. Setup refreshVersions for the project
4. Add lifecycle libs to  Android app's `build.gradle` file:
```
implementation(AndroidX.lifecycle.viewModelKtx)
implementation(AndroidX.lifecycle.liveDataKtx)
implementation(AndroidX.lifecycle.runtimeKtx)
implementation(AndroidX.lifecycle.viewModelSavedState)
implementation(AndroidX.lifecycle.commonJava8)

implementation("androidx.lifecycle:lifecycle-viewmodel-compose:_")
```
5. Try to build
6. See the error

**Comment by LouisCAD** [comment]
Hello, we are aware of these issues, and we want to provide a general solution for these so it cannot happen again. That will take some time though, and we're busy writing the contributing guide (plus day jobs and lives) right now.

In the meantime, the best solution is to hardcode the version for these compose related artifacts.

**Comment by KirillAmurskiy** [comment]
Thank you! I look forward to news!

**Comment by LouisCAD** [comment]
Version 0.10.0 is out with the fix!
In fact, all of the AndroidX dependency notations have been thoroughly reviewed and checked.
