### ISSUE TITLE
Constraint layout and compose constraint layout conflict

### ISSUE THREAD

**Issue by simonsickle** [jmfayard/refreshVersions#325]
**Checklist**

- [x] I tried to reproduce the bug in my fork of the [Kotlin Libraries Playground](https://github.com/LouisCAD/kotlin-libraries-playground), or in one of the samples in this repository
- [ ] I have run with `$ ./gradlew --scan refreshVersions` to [provide a Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg)

**Describe the bug**

When using the jetpack compose constraint layout library with the legacy library, the versions conflict and must be manually defined. 

**To Reproduce**

Build scan URL: https://scans.gradle.com/s/xxxxxxxxxx

1. Add constraint layout (legacy) to build.gradle (v2.0.4)
2. Add constraint layout (compose) to build.gradle (v1.0.0-alpha03)
3. Try to sync, notice it syncs fine
4. Replace versions with underscores
5. Notice that versions.properties fills out with `version.androidx.constraintlayout=2.0.4`

**Expected behavior**

The constraint layout compose library should get its own separate version entry so that I do not need to define it manually in my gradle file.

**Additional context**

https://maven.google.com/web/index.html#androidx.constraintlayout:constraintlayout-compose:1.0.0-alpha03
https://maven.google.com/web/index.html#androidx.constraintlayout:constraintlayout:2.0.4

**Comment by LouisCAD** [comment]
Hello, I just wanted to tell you I acknowledged the issue, and I'll provide a solution in the next release.

**Comment by LouisCAD** [comment]
Version 0.10.0 is out with the fix!
