### ISSUE TITLE
Allow manual comment in versions.propertiers

### ISSUE THREAD

**Issue by hkhc** [jmfayard/refreshVersions#329]
**Is your feature request related to a problem? Please describe.**

It would be useful if we could have our own comment in the versions.properties, in addition to the generated comments for available versions of dependencies. 

There are situations that newer versions dependencies are available, and we don't want to update for some reasons. However, we cannot add our own comment to versions.properties to record the reason why we don't want to update.

**Describe the solution you'd like**

I imagine it would be nice if we could add comment to versions.properties like this:
(triple hash means manually added comment, that shall stick with the dependency declarion)

```
### don't update to 2.34-beta until version.androidx.hilt=1.0.0-beta01 is available
version.google.dagger.hilt=2.33-beta
##             # available=2.34-beta
##             # available=2.34.1-beta
```

**Comment by LouisCAD** [comment]
Hello, this is planned, and in fact, already implemented.

I'll try to get the release ready sometime this week.

**Comment by LouisCAD** [comment]
Hello, the release is late, but it's still closer.
Thanks for your patience.

**Comment by LouisCAD** [comment]
Hello, the version 0.10.0 is out with support for comments!
