### ISSUE TITLE
Sometimes hundreds of dev versions are proposed by refreshVersions

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#343]
See for example inside http4k

> version.com.graphql-java..graphql-java=16.2

https://github.com/http4k/http4k/blob/380ec8a26cea303adeec7cde23e051caeb329dcf/versions.properties#L40-L575

**Comment by vlsi** [comment]
```
version.commons-collections..commons-collections=3.2.1
##                                   # available=3.2.2
##                                   # available=20030418.083655
##                                   # available=20031027.000000
##                                   # available=20040102.233541
##                                   # available=20040616
```

```
version.commons-pool..commons-pool=1.6
##                     # available=20020501
##                     # available=20030623.172700
##                     # available=20030818.195203
##                     # available=20030821.192746
##                     # available=20030825.183949
```

What do you think if the plugin ignores versions released more than one year than the currently used version?

For instance, [commons-pool versions](https://search.maven.org/artifact/commons-pool/commons-pool) are as follows:

1.4 -- 16-Jan-2008
‎1.0.1 -- 24-Nov-2005
20030623.172700 -- 09-Nov-2005
20030825.183949 -- 09-Nov-2005

WDYT?

**Comment by LouisCAD** [comment]
I don't think the release dates or timestamps are part of the maven metadata that we can get from repositories.

I might be wrong, but I recall trying to find such a thing twice, with no success.

**Comment by vlsi** [comment]
You are right, the timestamp is not a part of metadata: https://repo1.maven.org/maven2/commons-pool/commons-pool/maven-metadata.xml :(

How about creating a curated list of exclusions then?

**Comment by LouisCAD** [comment]
That's what I plan to do. I wish versioning was more conventional and strict through the Maven ecosystem.

**Comment by jmfayard** [comment]
This will be solved by `rejectVersionsIf`

https://github.com/jmfayard/refreshVersions/pull/347
