### ISSUE TITLE
Replace duplicated gradle wrappers by symlink and add samples CI check for 6.3+

### ISSUE THREAD

**Issue by LouisCAD** [jmfayard/refreshVersions#357]

**Comment by NikkyAI** [comment]
symlinks make development really annoying on windows,
how about using the `wrapper` task instead in the samples?

**Comment by LouisCAD** [comment]
> how about using the wrapper task instead in the samples?

Can you be more specific?
I'm not sure how it would be used to avoid duplicates in the repo.

**Comment by NikkyAI** [comment]
idea can use the wrapper task to get the correct gradle version
and the `gradle/` directory in the sampels can be gitignored

**Comment by jmfayard** [comment]
I'm sorry, I tried it a couple of times but it didn't work.
We can live with the duplication I guess
