### ISSUE TITLE
Output JSON?

### ISSUE THREAD

**Issue by timrijckaert** [jmfayard/refreshVersions#377]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)

## JSON output
To further automate dependency updates in our CI pipeline we are hoping this plugin would export the available updates in a JSON format. 
We could then pick up this JSON to automate ticket creation in Jira/Bitbucket/TeamCity/Gitlab...

## 💡 Describe the solution you'd like
It could work similarly to [Ben Manes' Gradle Versions Plugin](https://github.com/ben-manes/gradle-versions-plugin#report-format).

A new 'output' option in the `refreshVersions { }` block which can be used to configure this?

## 🤚 Do you want to develop this feature yourself?
- [x] Yes; with some directions from you guys.
- [x] No

**Comment by LouisCAD** [comment]
Did you just check every box without reading the template at all? 🤔

**Comment by timrijckaert** [comment]
No, i read everything....

**Comment by LouisCAD** [comment]
You can simply change the text of the template next time to make it clearer 😉

**Comment by LouisCAD** [comment]
Note that in the current form, you can have a CI job that runs the refreshVersions task and lets you know when there's new available versions (by simply detecting if the file changed).

Isn't that suiting your needs already?

**Comment by timrijckaert** [comment]
> Isn't that suiting your needs already?

Not really we want to be able have the full meta data of the dependency states.

The JSON could include for MVP 1:
- outdated dependencies:
  -  amount
  -  current version
  - list of new versions

Similar to the output Ben Manes' Version plugin can generate the following JSON.

<summary>Json report</summary>

```json
{
  "current": {
    "dependencies": [
      {
        "group": "backport-util-concurrent",
        "version": "3.1",
        "name": "backport-util-concurrent",
        "projectUrl": "https://backport-jsr166.sourceforge.net/"
      },
      {
        "group": "backport-util-concurrent",
        "version": "3.1",
        "name": "backport-util-concurrent-java12",
        "projectUrl": "https://backport-jsr166.sourceforge.net/"
      }
    ],
    "count": 2
  },
  "gradle": {
    "enabled": true,
    "current": {
      "version": "4.7",
      "reason": "",
      "isUpdateAvailable": true,
      "isFailure": false
    },
    "nightly": {
      "version": "4.9-20180526235939+0000",
      "reason": "",
      "isUpdateAvailable": true,
      "isFailure": false
    },
    "releaseCandidate": {
      "version": "4.8-rc-2",
      "reason": "",
      "isUpdateAvailable": true,
      "isFailure": false
    },
    "running": {
      "version": "4.6",
      "reason": "",
      "isUpdateAvailable": false,
      "isFailure": false
    }
  },
  "exceeded": {
    "dependencies": [
      {
        "group": "com.google.guava",
        "latest": "16.0-rc1",
        "version": "99.0-SNAPSHOT",
        "name": "guava",
        "projectUrl": "https://code.google.com/p/guava-libraries"
      },
      {
        "group": "com.google.guava",
        "latest": "16.0-rc1",
        "version": "99.0-SNAPSHOT",
        "name": "guava-tests",
        "projectUrl": "https://code.google.com/p/guava-libraries"
      }
    ],
    "count": 2
  },
  "outdated": {
    "dependencies": [
      {
        "group": "com.google.inject",
        "available": {
          "release": "3.0",
          "milestone": null,
          "integration": null
        },
        "version": "2.0",
        "name": "guice",
        "projectUrl": "https://code.google.com/p/google-guice/"
      },
      {
        "group": "com.google.inject.extensions",
        "available": {
          "release": "3.0",
          "milestone": null,
          "integration": null
        },
        "version": "2.0",
        "name": "guice-multibindings",
        "projectUrl": "https://code.google.com/p/google-guice/"
      }
    ],
    "count": 2
  },
  "unresolved": {
    "dependencies": [
      {
        "group": "com.github.ben-manes",
        "version": "1.0",
        "reason": "Could not find any version that matches com.github.ben-manes:unresolvable:latest.milestone.",
        "name": "unresolvable"
      },
      {
        "group": "com.github.ben-manes",
        "version": "1.0",
        "reason": "Could not find any version that matches com.github.ben-manes:unresolvable2:latest.milestone.",
        "name": "unresolvable2"
      }
    ],
    "count": 2
  },
  "count": 8
}
```
</details>

**Comment by LouisCAD** [comment]
It looks like you want exactly what Ben Manes plugin provides.

There's nothing preventing you from using both in the same project AFAIK, so I guess you can simply use it for the CI, and use refreshVersions locally?

**Comment by timrijckaert** [comment]
I see, I thought this plugin was more of a replacement.

**Comment by LouisCAD** [comment]
I personally don't need the CI part, I just remember to run refreshVersions on a regular basis, I commit the changes even if I don't upgrade. That way, I can see what are the new versions since last time.

The approach is different, and we believe it's better like that because it doesn't push to always upgrade, but gives information at the right place instead, giving more control to the developers so they integrate it in their workflow, without depending on a complex CI setup.
