### ISSUE TITLE
Add support for dependencyResolutionManagement

### ISSUE THREAD

**Issue by sgraca** [jmfayard/refreshVersions#379]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)

## ⚠️ Is your feature request related to a problem? Please describe
I tried to apply refreshVersions plugin to a Gradle project that declared repositories using [dependencyResolutionManagement](https://docs.gradle.org/6.8/userguide/declaring_repositories.html#sub:centralized-repository-declaration) in `settings.gradle` instead of declaring them in `build.gradle`. The plugin did not discover new versions of dependencies used. When I moved repositories declaration back to `build.gradle` new dependencies versions were reported.
It took me a while to figure out why the plugin did not work.

## 💡 Describe the solution you'd like
If repositories are declared using `dependencyResolutionManagement` the plugin scans them for new dependencies versions.

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by LouisCAD** [comment]
Hello, this is now supported in 0.30.0, just released.
