### ISSUE TITLE
RefreshVersionsUpgradeMigrationTest fails on windows

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#381]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)

## 🐛 Describe the bug
Emil Kantis has the `RefreshVersionsUpgradeMigrationTest` tests failing on windows on the main branch.

It's maybe a line-ending issue, windows vs Unix

https://scans.gradle.com/s/gnarprlxyycn6/tests/:refreshVersions:test/de.fayard.refreshVersions.migration.upgrade.RefreshVersionsUpgradeMigrationTest/test%20removal%20of%20migration%20call%20for%20Gradle%20Groovy%20DSL()?top-execution=1

## 📱 Tech info
 - [Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg): : https://scans.gradle.com/s/gnarprlxyycn6

**Comment by Kantis** [comment]
Also affected:
* `VersionsPropertiesModelTest`

**Comment by LouisCAD** [comment]
@jmfayard I think the solution might be to replace all `appendln()` calls with a copy of Kotlin 1.4 `appendLine()` which always appends `\n`.

**Comment by Kantis** [comment]
If test resources depend on using a specific style of line-endings they should be enforced with `.gitattributes`, or the tests must be re-written to be line-ending agnostic (preferable I believe). Even if `\n` is always used by production-code, some Windows-contributor working with the resources might check in something with `\r\n`

**Comment by LouisCAD** [comment]
Looks like you can't even clone the repository on Windows…
<img width="1003" alt="Screenshot 2022-01-23 at 23 24 53" src="https://user-images.githubusercontent.com/6975237/150700535-c28892bd-12bb-433a-918b-08d6f718cf35.png">

https://github.com/jmfayard/refreshVersions/runs/4915163032?check_suite_focus=true

**Comment by LouisCAD** [comment]
Found a workaround for the file path length issue, however, I am unable to see the exact failure reason through the logs or through the Gradle scan:

https://scans.gradle.com/s/sinfl72i4iliw/tests/:refreshVersions:test/de.fayard.refreshVersions.migration.upgrade.RefreshVersionsUpgradeMigrationTest/test%20removal%20of%20migration%20call%20for%20Gradle%20Groovy%20DSL()?top-execution=1

I copied the two but the diff window in my IDE tells me they are the same.

@Kantis Can you run the test locally on your Windows machine (with the latest `main` branch), then open the difference in a diff window (there should be a clickable "link" in the test failure logs for that), screenshot that and post it here so I can see what the mismatch is about? That'd be very helpful.

**Comment by LouisCAD** [comment]
Found the culprit, it was as you suggested, I added a proper `.gitattributes` file to ensure the line endings are kept in `LF` except for the `.bat` files (i.e. for the Windows Gradle wrapper).

Thank you.
