### ISSUE TITLE
Add Stately

### ISSUE THREAD

**Issue by brady-aiello** [jmfayard/refreshVersions#388]
- [X] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)

## ⚠️ Is your feature request related to a problem? Please describe
Stately is a common KMM library for native threading, and we'd like to use it in `refreshVersions`, to get away from `buildSrc` completely.
https://github.com/touchlab/Stately
How we're using it for safe multithreading on native in KaMP Kit:    https://github.com/touchlab/KaMPKit/blob/main/shared/src/commonMain/kotlin/co/touchlab/kampkit/ktor/DogApiImpl.kt#L39

## 💡 Describe the solution you'd like
Just adding the 4 most common KMM dependencies:
- `co.touchlab:stately-common`
- `co.touchlab:stately-concurrency`
- `co.touchlab:stately-isolate`
- `co.touchlab:stately-iso-collections`

Not going to include all of the individual platform artifacts, just the KMM ones, as the individual artifacts by themselves don't serve much use. The `common` artifact will add the right ones for your various targets. Also, not including `stately-collections` as it is ["pretty much deprecated"](https://github.com/touchlab/Stately#stately-collections)

## 🤚 Do you want to develop this feature yourself?

- [X] Yes
- [ ] No

**Comment by starsep** [comment]
This issue can be closed: has been fixed by #428
