### ISSUE TITLE
Add Multiplatform Settings

### ISSUE THREAD

**Issue by brady-aiello** [jmfayard/refreshVersions#390]
- [X] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)

## ⚠️ Is your feature request related to a problem? Please describe
@russhwolf's [Multiplatform Settings](https://github.com/russhwolf/multiplatform-settings) library is a go-to for making a KMM app, and I'd like to use it with refreshVersions.

How an example using it for multiplatform key-value store in KaMP Kit:    https://github.com/touchlab/KaMPKit/blob/main/shared/src/commonMain/kotlin/co/touchlab/kampkit/models/BreedModel.kt#L89

## 💡 Describe the solution you'd like
Just adding the common multiplatform dependencies:
- `com.russhwolf:multiplatform-settings`
- `com.russhwolf:multiplatform-settings-coroutines`
- `com.russhwolf:multiplatform-settings-coroutines-native-mt`
- `com.russhwolf:multiplatform-settings-datastore`
- `com.russhwolf:multiplatform-settings-no-arg`
- `com.russhwolf:multiplatform-settings-serialization`
- `com.russhwolf:multiplatform-settings-test`

Not going to include all of the individual platform artifacts, just the KMM ones, as the individual artifacts by themselves don't serve much use. The `common` artifact will add the right ones for your various targets.

## 🤚 Do you want to develop this feature yourself?

- [X] Yes
- [ ] No

**Comment by starsep** [comment]
This issue can be closed: has been fixed by #391
