### ISSUE TITLE
New version of MockK missed-out

### ISSUE THREAD

**Issue by iainism** [jmfayard/refreshVersions#393]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug
The latest version of MockK is 1.1.12: https://search.maven.org/search?q=mockk

However, even after running refreshVersions, my versions.properties only contains `version.io.mockk..mockk=1.11.0`

This is also visible in kotlin-libraries-playground: https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/versions.properties

## ⚠️ Current behavior
See above

## ✅ Expected behavior
New version is suggested

## 💣 Steps to reproduce
See above!

**Comment by jmfayard** [comment]
@iainism it works for me
https://github.com/LouisCAD/kotlin-libraries-playground/blob/f0f76b034b8f3b6f3816993b54cd4fd1241446b8/versions.properties#L262-L263

maybe you didn't add the relevant repository?

I have 

```
    repositories {
        mavenLocal()
        mavenCentral()
        google()
        jcenter()
    }
    ````

**Comment by iainism** [comment]
OK, so now it gets really weird.  I had a duplicated version entry for `version.mockk` (no idea how) and of course it was the later one that was getting the update, while I was looking at the first one!  I've taken out the duplicate and all is right again!

**Comment by LouisCAD** [comment]
In a future release (should be the next), unused version entries will be marked as such after running the `refreshVersions` task with a meta comment, so you don't think it's used when it's actually not.
