### ISSUE TITLE
Plugin  for Android Studio dosent work on the  Aritic Fox Version

### ISSUE THREAD

**Issue by lihuiqiang123** [jmfayard/refreshVersions#394]
please fix it . Thanks!
![image](https://user-images.githubusercontent.com/24646098/128015490-0c2fd8f0-1a5d-468d-a327-a21517b67185.png)

![image](https://user-images.githubusercontent.com/24646098/128015362-ca47f52c-0963-45a7-88cc-eeaec202ca06.png)

**Comment by jmfayard** [comment]
@lihuiqiang123 
I think you are using the old plugin `buildSrcVersions` instead of refreshVersions with `enableBuildSrcLibs()`
See http://127.0.0.1:8000/setup/#if-you-are-upgrading-from-the-buildsrcversions-plugin

**Comment by jmfayard** [comment]
Please re-open if my suggestion doesn't work

**Comment by lihuiqiang123** [comment]
It`s ok . Thank you very much!
