### ISSUE TITLE
refreshVersionsMigrate task is touching non-versions

### ISSUE THREAD

**Issue by necatisozer** [jmfayard/refreshVersions#398]
The **`refreshVersionsMigrate`** ~~`refreshVersionsCleanup`~~ task has converted
this
`buildConfigField("String", "BUILD_TIME", "\"${new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ").format(new Date())}\"")`
to that
`buildConfigField("String", "BUILD_TIME", "\"${new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:_").format(new Date())}\"")`

**Comment by LouisCAD** [comment]
Hello, it's impossible that the `refreshVersionsCleanup` has caused this.

I think you meant the `refreshVersionsMigrate` task, which is experimental.

Thank you for raising this, we'll improve it, so future migrations don't lead to this inconvenience.

**Comment by necatisozer** [comment]
> I think you meant the `refreshVersionsMigrate` task, which is experimental.


Yep. Thanks for correction.

**Comment by jmfayard** [comment]
Thanks @necatisozer , I fixed it https://github.com/jmfayard/refreshVersions/commit/ee6fab3c035013fc7982d5dd08d5bc453060e2cd

**Comment by LouisCAD** [comment]
@jmfayard Regarding your fix: I think the correct resolution is to touch things only from within the `dependencies` blocks, as we had discussed earlier.

Otherwise, we risk touching other things, including other values for `buildConfigField`.
