### ISSUE TITLE
build with androidx.core:core-splashscreen fails

### ISSUE THREAD

**Issue by sproctor** [jmfayard/refreshVersions#400]
- [ X] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug
For the dependency "androidx.core:core-splashscreen" it uses the version for the dependency "androidx.core:core-ktx"

## ⚠️ Current behavior
There is a line in my versions.properties: `versions.androidx.core=1.6.0`. refreshVersions uses that for the version for androidx.core:core-splashscreen, which is invalid.

## ✅ Expected behavior
I expect core-splashscreen to have its own version number, since the most recent version as of today is 1.0.0-alpha01

## 💣 Steps to reproduce
Include core-splashscreen and core-ktx in the same project.

**Comment by jmfayard** [comment]
Thanks for the report

You can hardcode the version to work-around the problem for now

`implementation(androidx.core:core-splashscreen:1.0.0-alpha01)`

**Comment by LouisCAD** [comment]
Fixed on main, next release will bring the dependency notation `AndroidX.core.splashscreen` and the correct version key will be used.

**Comment by LouisCAD** [comment]
0.20.0 is out, fixing this issue.

**Comment by sproctor** [comment]
Thank you, much appreciated.
