### ISSUE TITLE
Is it possible to have different version even it's inside a same group?

### ISSUE THREAD

**Issue by mochadwi** [jmfayard/refreshVersions#403]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug

Been curious if from the library author has differences (or deleted versions), how to allow different version on the same group inside `versions.properties`?

Maybe I'm missing the docs? or maybe incorrect keyword to search? :pray:

<img width="1006" alt="Screen Shot 2021-08-12 at 6 16 59 PM" src="https://user-images.githubusercontent.com/7057959/129188051-2ca68b08-0e0c-486b-b06c-ac5874dfe565.png">

## ⚠️ Current behavior

https://maven.google.com/web/#androidx.lifecycle:lifecycle-extensions:2.3.0 (not found, unless using: `2.2.0`)

https://maven.google.com/web/#androidx.lifecycle:lifecycle-livedata:2.3.0

the `lifecycle-extensions` was not found (intended), because using version of `2.3.0` in a same group (`androidx.lifecycle`)

## ✅ Expected behavior

Able to have a different versions for different dependencies(?)

## 💣 Steps to reproduce

Add "AndroidX" library that inside a same group but has a different version

## 📱 Tech info
 - [Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg):

**Comment by jmfayard** [comment]
The AndroidX dependencies are annoying because they don't follow a coherent versioning.

Since there is an opt-in mechanism - refreshVersions only handles versions with the underscore placeholder `_` - you can force different versions by hardcoding the version in build.gradle

`implementation("androidx.lifecycle:lifecycle-extensions:2.2.0")`

**Comment by mochadwi** [comment]
> > The AndroidX dependencies are annoying because they don't follow a coherent versioning.
> > Since there is an opt-in mechanism - refreshVersions only handles versions with the underscore placeholder `_` - you can force different versions by hardcoding the version in build.gradle
> > `implementation("androidx.lifecycle:lifecycle-extensions:2.2.0")`
> 
> after the hardcoded done, should we execute `./gradlew refreshVersionsMigrate` to move it into `versions.properties`?

whoops, trying this doesn't works, so we exclude the `lifecycle-extensions` from `./gradlew refreshVersions` then? cmiiw
