### ISSUE TITLE
Firebase Crashlytics Gradle Plugins become unresolved after migrating to `versions.properties`

### ISSUE THREAD

**Issue by mochadwi** [jmfayard/refreshVersions#405]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug

Really not sure if this is `firebase-crashlytics-gradle` issue or `refreshVersions`, before adding the `refreshVersions`, we were able to use any gradle API from `firebase-crashlytics-gradle`. 

## ⚠️ Current behavior

<img width="740" alt="Screen Shot 2021-08-12 at 6 49 14 PM" src="https://user-images.githubusercontent.com/7057959/129192239-1b7a872d-8937-4083-a0e5-72edf7001c8c.png">
<img width="565" alt="Screen Shot 2021-08-12 at 6 49 27 PM" src="https://user-images.githubusercontent.com/7057959/129192248-89d106a3-0e01-4dda-a6c0-8bd9b151328a.png">
<img width="1412" alt="Screen Shot 2021-08-12 at 6 50 05 PM" src="https://user-images.githubusercontent.com/7057959/129192252-e060ae0d-c5a4-4930-8c0e-0f98645ea752.png">
<img width="365" alt="Screen Shot 2021-08-12 at 6 51 02 PM" src="https://user-images.githubusercontent.com/7057959/129192259-e7f9139d-b546-45fa-8a6b-22e5a6544bbd.png">

## ✅ Expected behavior

The `refreshVersions` able to coexist with `firebase-crashlytics-gradle`

## 💣 Steps to reproduce

Not sure what/which information to provide here, but here's my config:

```
// versions.properties
version.firebase-crashlytics-gradle=2.7.1
```

```
// app/build.gradle.kts
plugins {
    // ... omitted
    id("com.google.firebase.crashlytics")
}
```

```
// buildSrc/settings.gradle.kts
pluginManagement {
    plugins {
        id("de.fayard.refreshVersions") version "0.11.0"
    }
}

plugins {
    id("de.fayard.refreshVersions")
}
```

```
// settings.gradle.kts
plugins {
    id("de.fayard.refreshVersions") version "0.11.0"
}
```

## 📱 Tech info
 - [Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg):

**Comment by LouisCAD** [comment]
You need to use the `no-BoM` variant. 

Unfortunately, the issue is that the Firebase BoM used to include the Gradle plugin, but no longer does.

We have a plan to improve our dependency notations so that the default is the working one.

**Comment by mochadwi** [comment]
> You need to use the `no-BoM` variant.
> 
> Unfortunately, the issue is that the Firebase BoM used to include the Gradle plugin, but no longer does.
> 
> We have a plan to improve our dependency notations so that the default is the working one.

Ahhh, noted, yes, we're currently using BoM for Firebase, well noted then, will use the `no-BoM` for a workaround for this, will gives you updates 🙏

**Comment by mochadwi** [comment]
> > You need to use the `no-BoM` variant.
> > Unfortunately, the issue is that the Firebase BoM used to include the Gradle plugin, but no longer does.
> > We have a plan to improve our dependency notations so that the default is the working one.
> 
> Ahhh, noted, yes, we're currently using BoM for Firebase, well noted then, will use the `no-BoM` a workaround for this, will gives you updates 🙏

This is so unfortunate, after using the `no-BoM` variant, the firebase plugin still fails to resolve 🙏 

![Screen Shot 2021-08-13 at 4 17 42 PM (2)](https://user-images.githubusercontent.com/7057959/129335260-106572a6-a7c1-409b-b19d-b5fa8feb74a4.png)

**Comment by LouisCAD** [comment]
You have a clash between your dependencies and the ones from refreshVersions.

The Firebase object from refreshVersions is used and uses camelCase, not snake_case.

**Comment by LouisCAD** [comment]
@jmfayard Can we make buildSrcLibs avoid clashes like that one?

**Comment by mochadwi** [comment]
> You need to use the `no-BoM` variant.
> 
> Unfortunately, the issue is that the Firebase BoM used to include the Gradle plugin, but no longer does.
> 
> We have a plan to improve our dependency notations so that the default is the working one.

Does this issue already opened, or should I create a feature request for this one?

**Comment by mochadwi** [comment]
> You have a clash between your dependencies and the ones from refreshVersions.
> 
> The Firebase object from refreshVersions is used and uses camelCase, not snake_case.

We've removed clashed dependencies from our `buildSrc`, unfortunately the firebase crashlytics plugins still failed to resolved :sob:

![Screen Shot 2021-08-16 at 1 54 34 PM](https://user-images.githubusercontent.com/7057959/129524061-831f4ed1-19b4-43bc-b4ec-128d60793ea8.png)
![Screen Shot 2021-08-16 at 1 55 14 PM](https://user-images.githubusercontent.com/7057959/129524070-649348c4-7c8c-4958-b018-770ec341a4cb.png)
![Screen Shot 2021-08-16 at 1 55 44 PM](https://user-images.githubusercontent.com/7057959/129524073-6481e7d5-2f87-4eae-a0d5-0ef7b54258d4.png)

**Comment by LouisCAD** [comment]
Next version of refreshVersions will improve bundled Firebase dependency notations. Hopefully, it helps.

In the meantime, just stick to plain hardcoded dependency notations and use the version placeholder (the underscore `_`).

**Comment by mochadwi** [comment]
> Next version of refreshVersions will improve bundled Firebase dependency notations. Hopefully, it helps.
> 
> In the meantime, just stick to plain hardcoded dependency notations and use the version placeholder (the underscore `_`).

Removing our previous `buildSrc/Dependencies.kt` and use hardcoded notation & version placeholder, unfortunately failed to resolve as well :(

**Comment by LouisCAD** [comment]
refreshVersions 0.20.0 is out with updated dependency notations. If it still doesn't work on your end, please link us a minimal reproducing project.

**Comment by mochadwi** [comment]
[android-agentapp.zip](https://github.com/jmfayard/refreshVersions/files/7037023/android-agentapp.zip) here's our private internal project, we also remove everything from credentials and our entire codebase, except the build.gradle(.kts) and a few scripting files

**Comment by mochadwi** [comment]
> [android-agentapp.zip](https://github.com/jmfayard/refreshVersions/files/7037023/android-agentapp.zip) here's our private internal project, we also remove everything from credentials and our entire codebase, except the build.gradle(.kts) and a few scripting files

we also update to `v0.22.0`, there's a little problems for this code (so we commented out for a while):

```kotlin
// implementation(Square.Retrofit2.retrofit) {
    //     exclude(group = "com.squareup.okhttp3")
    //     because("version 3.x pulled from retrofit")
    // }
```

please let us know if need anything 🙏  thank you ❤️

**Comment by LouisCAD** [comment]
It's 0.20.0, not 0.22.0, did are you sure you set the correct version?

**Comment by LouisCAD** [comment]
The issue is that `firebaseCrashlytics { … }` doesn't exist, because it's not optimized for Kotlin DSL, and I think you migrated from Groovy DSL which can go through runtime hacks to get that working. It's unrelated to refreshVersions itself.

**Comment by mochadwi** [comment]
> The issue is that `firebaseCrashlytics { … }` doesn't exist, because it's not optimized for Kotlin DSL, and I think you migrated from Groovy DSL which can go through runtime hacks to get that working. It's unrelated to refreshVersions itself.

looks like this is issue on firebase gradle plugins unsupported to GKD (Gradle Kotlin DSL) itself, cmiiw?

**Comment by LouisCAD** [comment]
BTW, posting big screenshots isn't very helpful to us. Giving the relevant part of the error messages, and any relevant small snippet is much less overwhelming for us, and we can sometimes reply when on mobile, which is hardly doable with these gigantic screenshots.

**Comment by mochadwi** [comment]
> BTW, posting big screenshots isn't very helpful to us. Giving the relevant part of the error messages, and any relevant small snippet is much less overwhelming for us, and we can sometimes reply when on mobile, which is hardly doable with these gigantic screenshots.

well noted, my apologize for the screenshot, I should've resize it before commenting :pray: :D

> because it's not optimized for Kotlin DSL, and I think you migrated from Groovy DSL which can go through runtime hacks to get that working

Thanks again for confirming this 🙏

**Comment by LouisCAD** [comment]
It supports it, but you cannot configure it the way you're doing. Just search for "firebase crashlytics kotlin dsl" on Google and you'll get the info you need to do what you want.

**Comment by mochadwi** [comment]
> It supports it, but you cannot configure it the way you're doing. Just search for "firebase crashlytics kotlin dsl" on Google and you'll get the info you need to do what you want.

found it!

for future readers, see workaround using this: 

```kotlin
// app/build.gradle.kts

plugins {
  //...
  id("com.google.firebase.crashlytics")
}

android {
  buildTypes {
    getByName("release") {
      (this as ExtensionAware).configure<CrashlyticsExtension> {
        mappingFileUploadEnabled = true
        nativeSymbolUploadEnabled = true
        // etc.
       }
    }
  }
}
```

or 

```kotlin
// app/build.gradle.kts
import com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsExtension

android {
  buildTypes{
        getByName("release") {
            configure<CrashlyticsExtension> {
                mappingFileUploadEnabled = false          // to disable mapping file uploads (default=true if minifying)
                nativeSymbolUploadEnabled = true         // to enable NDK symbol file uploading (default=false)
                unstrippedNativeLibsDir = "path/to/libs" // optional override to change the default unstripped native library path, only used in NDK builds 
            }
        }
    }
}
```

ref:

1. https://github.com/firebase/firebase-android-sdk/issues/1622#issuecomment-639584044
1. https://github.com/firebase/firebase-android-sdk/issues/2665#issuecomment-849897741
