### ISSUE TITLE
BomTest fails on CI, and only on CI

### ISSUE THREAD

**Issue by LouisCAD** [jmfayard/refreshVersions#412]
@jmfayard Do you have an idea why that happens?

https://github.com/jmfayard/refreshVersions/runs/3376450500?check_suite_focus=true

https://github.com/jmfayard/refreshVersions/runs/3376548081?check_suite_focus=true

**Comment by jmfayard** [comment]
I configured the test configuration with `Repeat > Until failure` and it systematically fails on the second run

<img width="1161" alt="Notification_Center" src="https://user-images.githubusercontent.com/459464/130219664-f750c3a0-f9ec-4a5d-bcc1-73ebaf186354.png">

**Comment by LouisCAD** [comment]
Thanks for the insights, I found the culprit and fixed it on main.
