### ISSUE TITLE
Dependency notations for InsertKoinIO/koin 

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#414]
## About the library(-ies)

- *Description*: Koin - a smart Kotlin injection library to keep you focused on your app, not on your tools 
- *GitHub*: https://github.com/InsertKoinIO/koin
- *Official website*: https://insert-koin.io

Gradle dependency notations available at https://insert-koin.io/docs/setup/v3

## Wants to contribute the sample?

- Say so in a comment here
- Follow [instructions for submitting dependency notations](https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dependency-notations-updates/)
- Submit your pull request!

**Comment by starsep** [comment]
This issue can be closed: has been fixed by #421
