### ISSUE TITLE
Dependency notations for Reactive libraries

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#416]
## About the library(-ies)

- *Description*: Reactive Streams is an initiative to provide a standard for asynchronous stream processing with non-blocking back pressure.
- *Official website*: http://www.reactive-streams.org/

- *Description*: Reactor is a fourth-generation reactive library, based on the Reactive Streams
specification, for building non-blocking applications on the JVM 
- *GitHub*: https://github.com/reactor
- *Official website*: https://projectreactor.io/

- *Description*:  RxJava – Reactive Extensions for the JVM – a library for composing asynchronous and event-based programs using observable sequences for the Java VM. 
- *GitHub*: https://github.com/ReactiveX/RxJava
- *Official website*: http://reactivex.io/

## Wants to contribute the sample?

- Say so in a comment here
- Follow [instructions for submitting dependency notations](https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dependency-notations-updates/)
- Submit your pull request!

**Comment by mgray88** [comment]
✋  I've started some work on the RxJava dependencies: #478

**Comment by imashnake0** [comment]
This can be closed as it was resolved in #499.

**Comment by jmfayard** [comment]
Thanks !
