### ISSUE TITLE
Dependency notations for arrow-kt/arrow

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#418]
## About the library(-ies)

- *Description*: Functional companion to Kotlin's standard library
- *GitHub*: https://github.com/arrow-kt/arrow
- *Official website*: https://arrow-kt.io/

Dependency notations available here: https://arrow-kt.io/docs/core/

## Wants to contribute the sample?

- Say so in a comment here
- Follow [instructions for submitting dependency notations](https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dependency-notations-updates/)
- Submit your pull request!

**Comment by jmfayard** [comment]
@imashnake0 No, create a top-level object `Arrow` like the others
Don't forget to reference it inside `_ALL.kt`
https://github.com/jmfayard/refreshVersions/tree/main/plugins/dependencies/src/main/kotlin/dependencies

**Comment by RFonzi** [comment]
I can grab this if no one's working on it

**Comment by imashnake0** [comment]
> I can grab this if no one's working on it

All yours!
