### ISSUE TITLE
Dependency notations for testing libraries

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#419]
## About the library(-ies)

[AssertJ - fluent assertions java library](https://assertj.github.io/doc/#assertj-core-quick-start)

[Hamcrest Matchers that can be combined to create flexible expressions of intent](http://hamcrest.org/JavaHamcrest/distributables)

[json-path/JsonPath: Java JsonPath implementation](https://github.com/json-path/JsonPath)

[skyscreamer/JSONassert: Write JSON unit tests in less code. Great for testing REST interfaces.](https://github.com/skyscreamer/JSONassert)

[JSONAssert - Write JSON Unit Tests with Less Code - Introduction](http://jsonassert.skyscreamer.org/)

[rest-assured/rest-assured: Java DSL for easy testing of REST services](https://github.com/rest-assured/rest-assured)

[cucumber/cucumber-jvm: Cucumber for the JVM](https://github.com/cucumber/cucumber-jvm)

[BDD Testing &amp; Collaboration Tools for Teams | Cucumber](https://cucumber.io/)

## Wants to contribute the sample?

- Say so in a comment here
- Follow [instructions for submitting dependency notations](https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dependency-notations-updates/)
- Submit your pull request!

**Comment by imashnake0** [comment]
@LouisCAD I'm working on this next, will have a draft PR out soon. I will also create issue(s) for some other testing libraries I have in mind.

**Comment by LouisCAD** [comment]
I'm not sure we should add them all though 🤔

**Comment by imashnake0** [comment]
> I'm not sure we should add them all though 🤔

Yep, there are some that it doesn't make sense to add (AssertJ Joda, for example), I'll list them out if I end up not adding them.
