### ISSUE TITLE
refreshVersions seems not to work with local nexus repository

### ISSUE THREAD

**Issue by StefanHirche** [jmfayard/refreshVersions#456]
- [ ] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug
refreshVersions seems not to work with local nexus repository

## ⚠️ Current behavior
We have a local nexus repository manager running, proxying also maven central and other services and holding own artifacs. When using this in the repositoy block like
```
buildscript {
    repositories {
        maven {
            url "http://nexus.company.com:8082/repository/product/"
            allowInsecureProtocol true
        }
    }
```
I get the error `Cannot get version candidates with an empty fetchers list.`
When I add mavenCentral(), pacakges from maven central are retreived, but for packages that are not on maven central, i get i.e.
```
Maven(group=com.github.jk1, name=gradle-license-report) not found. Searched the following repositories:
- https://repo.maven.apache.org/maven2/
```
## ✅ Expected behavior
With the dependency plugin everything works fine, but I would expect the refreshVersions plugin also work with proxy nexus repositories

## 💣 Steps to reproduce
Difficult. I can provide additional information on demand.

## 📱 Tech info
 - [Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg):

**Comment by LouisCAD** [comment]
Hello, do you have a way to use https instead?

**Comment by LouisCAD** [comment]
Hello, please answer the question above.

FYI, we decided to not support cleartext http because it's very easy to perform MITM (man-in-the-middle) attacks on it, and as you can see Gradle also disabled it by default.

**Comment by StefanHirche** [comment]
At the moment we can't support https, but if this is the reason it does not
work, I'm ok with this. Maybe a parameter to override this behaviour would
be great, to use http only on local repos.

Louis CAD ***@***.***> schrieb am So., 19. Dez. 2021, 00:45:

**Comment by LouisCAD** [comment]
Alright, thanks for the update.

Do you know a way to replicate your setup, so we can test it in one of our samples, and make changes confidently?

**Comment by StefanHirche** [comment]
Basically I just set up a nexus without https and mirror maven-central. Nothing special.
Ther is a parameter in gradle that I have to use t onot get a warning
buildscript {
	repositories {
		maven {
			url "http://***:***/repository/***-group/"
			allowInsecureProtocol true
		}
	}
	dependencies.classpath("de.fayard:dependencies:0.5.8")
}

**Comment by LouisCAD** [comment]
Looks like you're not using the right version of refreshVersions 🤔

**Comment by StefanHirche** [comment]
OK, i will test the current version. 
Just to remove all misunderstandings, in the code snippet i use the old depenency plugin.

**Comment by LouisCAD** [comment]
Yes, we discontinued it, its content is now part of the main refreshVersions plugin.

**Comment by LouisCAD** [comment]
Next version will support http repositories.
You can also use the version 0.32.0-SNAPSHOT immediately.

**Comment by LouisCAD** [comment]
Feature released in version 0.32.0

**Comment by StefanHirche** [comment]
Cool, i will try as soon as possible.

Louis CAD ***@***.***> schrieb am So., 9. Jan. 2022, 15:37:

**Comment by StefanHirche** [comment]
I just tested it, it's working. Thanks a lot.
