### ISSUE TITLE
Kotlin/JS NPM dependencies

### ISSUE THREAD

**Issue by CLOVIS-AI** [jmfayard/refreshVersions#457]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)

## ⚠️ Is your feature request related to a problem? Please describe
Currently, a typical Kotlin/JS project that uses refreshVersions might look like this:
```build.gradle.kts
dependencies {
	testImplementation(kotlin("test-js"))

	implementation(project(":client"))

	// Simplified by refreshVersions
	implementation(KotlinX.coroutines.coreJs)

	// Omitted version thanks to refreshVersions
	implementation("org.jetbrains.kotlin-wrappers:kotlin-react:_")
	implementation("org.jetbrains.kotlin-wrappers:kotlin-react-dom:_")

	// refreshVersions is currently unable to manage NPM dependencies
	implementation(npm("react", "17.0.2"))
	implementation(npm("react-dom", "17.0.2"))
}
```

## 💡 Describe the solution you'd like
The ability to use the `"_"` notation in NPM dependencies as well.

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

I currently have very little time and have never written Gradle plugins previously, however if it's a few simple changes I can find some time to do it. I don't have the knowledge for anything more involved, though.

**Comment by LouisCAD** [comment]
Hello, it is already supported

**Comment by CLOVIS-AI** [comment]
Ah, then it's just refreshVersionsMigrate that doesn't migrate it. Good to
know it works!

**Comment by LouisCAD** [comment]
Feel free to request that migration becomes supported for npm dependencies as well.
