### ISSUE TITLE
Using Firebase BoM with refreshVersions

### ISSUE THREAD

**Issue by imashnake0** [jmfayard/refreshVersions#459]
Hello, 
I had a quick question about how refreshVersions worked with Firebase BoM: I noticed two ways of declaring dependencies in the sample app; `implementation(Firebase.authentication)` and `implementation("com.google.firebase:firebase-analytics")`, does it matter which one I choose? How would I go about if I wanted to "override" the version designated in the BoM?

**Comment by LouisCAD** [comment]
Hello, we should definitely get documentation for that in refreshVersions.

The following will use the BoM properly:

```kts
dependencies {
    implementation(platform(Firebase.bom))
    implementation(Firebase.whatever)
}
```

The fact that `Firebase.bom` is used first enables the BoM mode for subsequent dependency notations from the same group.

**Comment by imashnake0** [comment]
I know it's not recommended but what if I wanted to [use a different library version than what's designated in the BoM? ](https://firebase.google.com/docs/android/learn-more#bom)

**Comment by LouisCAD** [comment]
Don't unless you're happy to break your app…

For non Firebase use cases, you can see what autocompletion suggests on these dependency notations, they have special extensions.

**Comment by imashnake0** [comment]
Sounds good, I was just curious :)
