### ISSUE TITLE
Can not update a kotest-extension to its latest release

### ISSUE THREAD

**Issue by tgrafford** [jmfayard/refreshVersions#465]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug

All kotest-extensions are grouped under the same alias, thereby using the same version, although all extensions are independently maintained.

## ✅ Expected behavior

All kotest-extensions should be independently versioned. Or in some way be able to override the default aliases provided by this library.

## 💣 Steps to reproduce

The following `build.gradle.kts`:
```kotlin
dependencies {
    testImplementation("io.kotest.extensions:kotest-extensions-spring:_")
    testImplementation("io.kotest.extensions:kotest-extensions-pitest:_")
}
```

Generates the following `versions.properties` when running `./gradlew refreshVersions`:
```properties
version.kotest-extensions=1.0.1
##            # available=1.0.2
##            # available=1.0.3
##            # available=1.0.4
##            # available=1.0.5
##            # available=1.0.6
```

But the latest version of [`kotest-extensions-spring`](https://github.com/kotest/kotest-extensions-spring) (as of writing) is 1.1.0, and the latest of [`kotest-extensions-pitest`](https://github.com/kotest/kotest-extensions-pitest) is 1.0.1. 
Setting `version.kotest-extensions=1.1.0` fails the download of `kotest-extensions-pitest` (as expected).

Attempt to adding the artifacts explicitly tags them as "unused", making it not possible to override this behavior:
```properties
## unused
version.io.kotest.extensions..kotest-extensions-spring=1.1.0

## unused
version.io.kotest.extensions..kotest-extensions-pitest=1.0.1

version.kotest-extensions=1.0.1
##            # available=1.0.2
##            # available=1.0.3
##            # available=1.0.4
##            # available=1.0.5
##            # available=1.0.6
```

**Comment by LouisCAD** [comment]
Hello again, this should be fixed in 0.30.1
