### ISSUE TITLE
Prevent adding https://repo.gradle.org/gradle/list/libs-releases to gradle configuration when using plugin

### ISSUE THREAD

**Issue by jschneidereit** [jmfayard/refreshVersions#466]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)

## ⚠️ Is your feature request related to a problem? Please describe
When operating in business, generally there is a requirement to use the internal artifact repository. Currently the docs only describe [how to add more repositories](https://jmfayard.github.io/refreshVersions/setup/#if-you-want-to-use-a-snapshot-version), not prevent them from being added.

## 💡 Describe the solution you'd like
Configuration is added to prevent external repositories from being added to plugin management.

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [ ] No

**Comment by LouisCAD** [comment]
Hello, I don't see how it's an issue in refreshVersions, you linked the documentation to use pre-releases, which I doubt is what you want to use as it can lead to non-reproducible builds and is only intended for short-term testing.

**Comment by jschneidereit** [comment]
The issue here is not libs-release, it's the existence of repo.gradle.org

**Comment by LouisCAD** [comment]
What are you calling "libs-release"?
