### ISSUE TITLE
Failed to resolve Firebase libraries (perf-ktx, analytics-ktx, crashlytics-ndk)

### ISSUE THREAD

**Issue by Endi327** [jmfayard/refreshVersions#467]
Hi,
I was trying to use refreshVersions with these firebase libraries: 
com.google.firebase:firebase-perf-ktx
com.google.firebase:firebase-crashlytics-ndk
com.google.firebase:firebase-analytics-ktx

I can see that all of those are generated in 0.23.0, but when I try to build my app I got the following error message:
**Failed to resolve: com.google.firebase:firebase-perf-ktx:**
**Failed to resolve: com.google.firebase:firebase-crashlytics-ndk:**
**Failed to resolve: com.google.firebase:firebase-analytics-ktx:**

<img width="413" alt="Screenshot 2021-12-16 at 11 34 23" src="https://user-images.githubusercontent.com/14042450/146355545-8750d094-ba0e-4ed6-bbe2-9611795e455c.png">

If I'm using hardcoded strings, it works fine. Can you help with this?

**Comment by LouisCAD** [comment]
Hello, you need to add a dependency to the BoM:
```kts
implementation(platform(Firebase.bom))`
```

**Comment by imashnake0** [comment]
@Endi327 Can you try adding `implementation(platform(Firebase.bom))` before all your other firebase SDKs and change the BoM version to [one that suits your needs](https://firebase.google.com/docs/android/learn-more#compare-bom-versions)? Note that in this case, you wouldn't need versions for the SDKs that use the BoM.

**Comment by LouisCAD** [comment]
The (bad) alternative is to suffix `.withVersionPlaceholder()` to all the Firebase.whatever` usages, this risks having version mismatches, and makes upgrading harder, so using BoM is best.

**Comment by Endi327** [comment]
> Hello, you need to add a dependency to the BoM:
> 
> ```kotlin
> implementation(platform(Firebase.bom))
> ```

Thanks that solved the issue!
