### ISSUE TITLE
Don't fail completely if a dependency's version info can't be found

### ISSUE THREAD

**Issue by toddobryan** [jmfayard/refreshVersions#468]
- [X] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)

## ⚠️ Is your feature request related to a problem? Please describe
An internal project owned by another team is not published correctly, so `refreshVersions` can't read its version. But when I try to run `refreshVersions`, it errors out and doesn't report any new versions. So my only choice is to either hard-code the version in `build.gradle`, or comment out the offending project so that the error doesn't happen. The first means all my versions wouldn't be in the same location. The second is a lot of fiddling every time I want to check versions.

## 💡 Describe the solution you'd like
If `refreshVersions` can't find a dependency, it should just put a comment (e.g., `# no version info could be found`) and add all the version info for the other dependencies, rather than erroring and not updating any of the versions.

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [X] No
but I'd be happy to. I suspect the hardest part would be figuring out where all this happens.

**Comment by LouisCAD** [comment]
Great suggestion! We had planned to work on allowing skipping failures but weren't sure how to do it yet, adding a comment might work well and stay contextual.

I'll get back to you after the next release.

If you were to spend time on that feature, would you want to develop it on your own with some guidance, or would you want us to pair-program it?

**Comment by toddobryan** [comment]
I could probably do it with some guidance.

**Comment by LouisCAD** [comment]
Can we have a chat on Kotlin Slack, or Telegram to find a time slot where we talk about how to design the feature and so I show you where you'll need to perform the edits?

**Comment by LouisCAD** [comment]
With jcenter doing 502 errors again, and the Gradle plugin portal (transitively?) doing 500 errors today, I'm going to work on this right now as it's blocking me.

**Comment by LouisCAD** [comment]
If you want to participate in this, please reach out via email (see my GitHub profile) or Kotlin Slack.

**Comment by LouisCAD** [comment]
Almost done.

**Comment by toddobryan** [comment]
Thank you, thank you, thank you! I got busy at work and didn't check back as I should have.
