### ISSUE TITLE
Dependency notations for Kermit

### ISSUE THREAD

**Issue by brady-aiello** [jmfayard/refreshVersions#480]
## About the library(-ies)

- *Description*: 
> Kermit is a Kotlin Multiplatform logging utility with composable log outputs. The library provides prebuilt loggers for outputting to platform logging tools such as Logcat and NSLog.

Post: https://medium.com/@kpgalligan/kermit-kmp-logging-1-0-196bf799b738
- *GitHub*: https://github.com/touchlab/Kermit
- *Official website* (if any, besides the GitHub page): NA

## Want to contribute the sample?

- I'll add this myself. Usage will be:
```kotlin
implementation(Touchlab.kermit.kermit)
implementation(Touchlab.kermit.test)
implementation(Touchlab.kermit.bugsnag)
implementation(Touchlab.kermit.bugsnagTest)
implementation(Touchlab.kermit.crashlytics)
implementation(Touchlab.kermit.crashlyticsTest)
```

**Comment by LouisCAD** [comment]
Released in version 0.32.0
