### ISSUE TITLE
Plugin with id 'de.fayard.buildSrcLibs' not found. - 0.30.2

### ISSUE THREAD

**Issue by Endi327** [jmfayard/refreshVersions#488]
- [ ] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug
Syncing Gradle project with Android Studio doesn't work anymore with the plugin set up in buildSrc. This used to work in version 0.23.0.  

## ⚠️ Current behavior

This is the error message when I sync.

```
`A problem occurred configuring root project ''.
> Plugin with id 'de.fayard.buildSrcLibs' not found.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project ''.
	blablabla
Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with id 'de.fayard.buildSrcLibs' not found.
	blablabla
	at org.gradle.kotlin.dsl.PluginAwareExtensionsKt.apply$default(PluginAwareExtensions.kt:31)
	at de.fayard.refreshVersions.RefreshVersionsPlugin$bootstrap$2$4$2.execute(RefreshVersionsPlugin.kt:151)
	at de.fayard.refreshVersions.RefreshVersionsPlugin$bootstrap$2$4$2.execute(RefreshVersionsPlugin.kt:16)
	blablabla
```

## ✅ Expected behavior
Sync completes successfully.

## 💣 Steps to reproduce
`settings.gralde` -> this is the app module settings.gradle
```
plugins {
    id("de.fayard.refreshVersions") version "0.30.2"
}

refreshVersions {
    featureFlags {
        enable(de.fayard.refreshVersions.core.FeatureFlag.LIBS)
        enableBuildSrcLibs()
    }
}
```

This how my buildSrc module looks like:
<img width="283" alt="Screenshot 2022-01-11 at 9 25 14" src="https://user-images.githubusercontent.com/14042450/148906849-3ff01da1-d48d-4af7-9d0d-e21686c72cf3.png">

This also not working on 0.30.1 or 0.30.0. 

I'm using these gradle versions:
`com.android.tools.build:gradle:7.0.4`
`https\://services.gradle.org/distributions/gradle-7.0.2-all.zip`

## 📱 Tech info

Reproduced on:

Android Studio Arctic Fox | 2020.3.1 Patch 2
Build #AI-203.7717.56.2031.7678000, built on August 26, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
Registry: external.system.auto.import.disabled=true

**Comment by jmfayard** [comment]
@Endi327 works for me on the latest version. 
See in the `sample-kotlin` Gradle project

https://github.com/jmfayard/refreshVersions/commit/bbf3e16e2c62aed46aba6c181aac7ceb5d71a0b6#diff-d01ba0f85dff4292897c3c5b42066b3777c06e89bd099064167715c491554f4a

I think you get the setup wrong, see here
https://jmfayard.github.io/refreshVersions/gradle-buildsrcversions/#long-life-to-gradle-buildsrclibs
