### ISSUE TITLE
Lib still pulling from JCenter ?

### ISSUE THREAD

**Issue by NabilEL** [jmfayard/refreshVersions#489]
Hello,

my builds are failing since this afternoon because Jcenter seems completely down now. I've removed every jcenter dependencies from my project but the lib seems to still pull from them : 

`What went wrong:
Could not resolve all artifacts for configuration 'classpath'.
> Could not resolve de.fayard.refreshVersions:refreshVersions-core:0.30.2.
  Required by:
      unspecified:unspecified:unspecified > de.fayard.refreshVersions:de.fayard.refreshVersions.gradle.plugin:0.30.2 > de.fayard.refreshVersions:refreshVersions:0.30.2
   > Could not resolve de.fayard.refreshVersions:refreshVersions-core:0.30.2.
      > Could not parse POM https://plugins.gradle.org/m2/de/fayard/refreshVersions/refreshVersions-core/0.30.2/refreshVersions-core-0.30.2.pom
         > Could not resolve com.google.cloud:libraries-bom:24.0.0.
            > Could not resolve com.google.cloud:libraries-bom:24.0.0.
               > Could not parse POM https://plugins.gradle.org/m2/com/google/cloud/libraries-bom/24.0.0/libraries-bom-24.0.0.pom
                  > Could not resolve com.google.cloud:google-cloud-bom:0.163.0.
                     > Could not resolve com.google.cloud:google-cloud-bom:0.163.0.
                        > Could not parse POM https://plugins.gradle.org/m2/com/google/cloud/google-cloud-bom/0.163.0/google-cloud-bom-0.163.0.pom
                           > Could not resolve com.google.cloud:google-cloud-bigqueryconnection-bom:2.1.5.
                              > Skipped due to earlier error
> Could not resolve org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.0.
  Required by:
      unspecified:unspecified:unspecified > de.fayard.refreshVersions:de.fayard.refreshVersions.gradle.plugin:0.30.2 > de.fayard.refreshVersions:refreshVersions:0.30.2 > org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0
   > Skipped due to earlier error`

https://plugins.gradle.org/m2/com/google/cloud/libraries-bom/24.0.0/libraries-bom-24.0.0.pom => redirects to jcenter
https://plugins.gradle.org/m2/com/google/cloud/google-cloud-bom/0.163.0/google-cloud-bom-0.163.0.pom => also redirects to jcenter

Is it possible to update your dependencies to pull from maven/jitpack ? Or is the issue somewhere else ?
Thanks.

**Comment by kevin-denver** [comment]
👍 I have experienced the same issue this afternoon. For some reason upgrading to Gradle 7.3 worked for me. Mind you I am still on version 0.23.0 of this plugin.

**Comment by LouisCAD** [comment]
Hello, the issue was caused by the fact that the Gradle plugin portal still delegates to jcenter, which is (was?) having issues today.

**Comment by LouisCAD** [comment]
@kevin-denver any reason you didn't upgrade to 0.30.2?
