### ISSUE TITLE
Add a task for just printing outdated dependencies to the console

### ISSUE THREAD

**Issue by sschuberth** [jmfayard/refreshVersions#490]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)

## ⚠️ Is your feature request related to a problem? Please describe

I'd like to stick to my own way of declaring dependency versions, but would like to use this plugin for checking for updates.

## 💡 Describe the solution you'd like

Having a new task that just prints outdated dependencies to the console (without migrating or updating anything and leaving files untouched) would be nice.

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by LouisCAD** [comment]
Hello,

You say:

> I'd like to stick to my own way of declaring dependency versions

Why?

**Comment by sschuberth** [comment]
It's probably just a personal matter-of-taste-thing, but I don't like the syntax of the modifications done to the build files by this plugin, esp. the `_` version placeholders and the consecutive `..` in property names.

**Comment by LouisCAD** [comment]
That's why we provide dependency notations with version keys for many dependencies related to the Kotlin ecosystem.

**Comment by sschuberth** [comment]
That approach does not scale, IMO.

**Comment by LouisCAD** [comment]
It's partly true, and we're fine with that.

However, the approach you're suggesting doesn't scale so well either as it requires more manual work to update dependencies versions.

**Comment by LouisCAD** [comment]
I prefer to be honest, I don't see myself spending hours and days on such a feature which I believe provides an inferior UX to what we already have, especially as it'd likely be unpaid work.

The consecutive `..` is a tradeoff to allow us to use the java properties format that is recognized by the IDE (`:` is a key value separator). We prefer to have that over no syntactic coloration.

**Comment by sschuberth** [comment]
> I don't see myself spending hours and days on such a feature

That's completely fine. I'm not necessarily asking *you* to add. I filed this to track this publicly, and if there is an agreement, *someone* from the community (including my) might implement it.

Or you can close this issue at your choice if you even wouldn't even take the feature if someone filed a PR for it.

> especially as it'd likely be unpaid work.

That's nothing you need to emphasize. We all do unpaid work in the many Open Source projects we contribute to.

**Comment by mgray88** [comment]
I'd like to submit another problem a feature like this might help with. Using refreshVersions in CI and getting a more easily parsable format for adding to a PR. `versions.properties` has a lot of information missing that would be needed for something like this: the actual package name, potentially the url of the dependency

**Comment by jmfayard** [comment]
@sschuberth given limited time and energy, we try to optiimize refreshVersions for people who use it, not for people who don't really use it.

I'm closing this at won't fix.

**Comment by mgray88** [comment]
@jmfayard I don't see how the use case is entirely separate from the original requested solution. A list of outdated dependencies, which I would imagine already exist in memory in some form while refreshVersions is running.

I could consider taking a look at implementing it, if you could give me a few pointers at where to look for declaring tasks, and where that list of dependencies would be stored while running

**Comment by jmfayard** [comment]
How would that help most people using refreshVersions?
