### ISSUE TITLE
Add new Kotlin dependency notations

### ISSUE THREAD

**Issue by LouisCAD** [jmfayard/refreshVersions#498]
dataframe, multik and lincheck are missing.

There's also https://github.com/JetBrains/KotlinDL

**Comment by jmfayard** [comment]
alles gut jetzt

![CleanShot 2022-09-13 at 23 40 23@2x](https://user-images.githubusercontent.com/459464/190014318-ad694831-4cb0-46a4-968d-423bd7502d1b.png)
