### ISSUE TITLE
Version is flagged as unused when it's only used by `versionFor()`

### ISSUE THREAD

**Issue by pvarry** [jmfayard/refreshVersions#511]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug
Version in `versions.properties` get unused when it's only used with `versionFor()`.

## ⚠️ Current behavior
My versions get `unused`

## ✅ Expected behavior
Do not add `unused` when it's used by `versionFor()`

## 💣 Steps to reproduce
- Create a new Android project (or use a existing one)
- Add Jetpack Compose to this project
- Add the folowing version : `version.androidx.compose.compiler=1.1.1`
- Add `composeOptions` in `build.gradle.kts` :

```kotlin
composeOptions {
    kotlinCompilerExtensionVersion = versionFor(AndroidX.compose.compiler)
}
```

- run `./gradlew refreshVersions` and see Compose Compiler get an unused in `versions.properties`

Note: Compose Compiler need to be used only in `versionFor` to be annotated with `unused`

## 📱 Tech info
 - [Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg): 

PS: Thanks for this wonderful library

**Comment by pvarry** [comment]
Hello, any news on this @jmfayard @LouisCAD ?

**Comment by LouisCAD** [comment]
Hello,
I just made an experiment to see if we can avoid this unwanted unused comment, and it should work, so I'll try to implement it soon.

We should also be able to factor these usages in when looking for available versions.

Thanks for raising this back.

**Comment by LouisCAD** [comment]
The `0.41.0-SNAPSHOT` version contains the change that addresses this issue.
I'll publish a release this weekend or next week.

**Comment by jmfayard** [comment]
Please don't override version `0.40.2-SNAPSHOT`@louiscad

Some people use it since months to get dependencies updates in their versions catalog

https://github.com/jmfayard/refreshVersions/pull/509

**Comment by LouisCAD** [comment]
I think the 0.40.2 release did remove the related snapshot, not this 0.41.0 snapshot.

**Comment by mcpiroman** [comment]
OK, but apparently the version is still not being updated by refreshVersions? I expect it to be as it is indeed used.

**Comment by LouisCAD** [comment]
@mcpiroman Wrong issue, or you're on an older version?

**Comment by mcpiroman** [comment]
I mean I have
```toml
[versions]
skiko = "0.7.42"
[libraries]
skiko = { module = "org.jetbrains.skiko:skiko", version.ref = "skiko" }
```
Then I do `api("org.jetbrains.skiko:skiko-awt-runtime-${targetOs}-${targetArch}:${versionFor("org.jetbrains.skiko:skiko:_")}")`
Then the update comments are not generated for skiko.

Is this maybe some other issue? I use 0.51.0

**Comment by LouisCAD** [comment]
Are you using configureOnDemand?
