### ISSUE TITLE
Dependency notations for  apollographql/apollo-kotlin 

### ISSUE THREAD

**Issue by imashnake0** [jmfayard/refreshVersions#518]
## About the library(-ies)

- *Description*: GraphQL client that generates Kotlin and Java models from GraphQL queries.
- *GitHub*: [apollographql/apollo-kotlin](https://github.com/apollographql/apollo-kotlin)
- *Official website* (if any, besides the GitHub page): [apollographql.com/docs](https://www.apollographql.com/docs/)

## Want to contribute the sample?

- Say so in a comment here
- Follow [instructions for submitting dependency notations](https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dependency-notations-updates/)
- Submit your pull request!

**Comment by thederputy** [comment]
I'm working on a PR for this, should have it done soon.

**Comment by imashnake0** [comment]
I should be able to get back on some of the issues assigned to me too. Been busy the past couple weeks 😔

**Comment by LouisCAD** [comment]
Thank you!
I'm assigning it to you @thederputy.

Naming wise, I thinj we want the following result at use site: `ApolloGraphQL.apollo3`.

@martinbonnin WDYT?

**Comment by thederputy** [comment]
I was thinking of keeping it terse rather than verbose, e.g, use site would look like:
```
implementation(Apollo.runtime)
testImplementation(Apollo.testingSupport)
androidTestImplementation(Apollo.idlingResource)
```

or 
```
implementation(Apollo.api)
implementation(Apollo.runtimeKotlin)
```

This sort of follows what `Arrow` is doing, in that it is named `Arrow` and not `ArrowKt`.

----

However, if support were to be added for other libraries in the `apollographql` account, then maybe the following approach would be better:
```
object ApolloGraphQL : IsNotADependency {
    object ApolloKotlin : DependencyGroup(
        group = "com.apollographql.apollo3",
        rawRules = """
        com.apollographql.apollo3:apollo-*
                                  ^^^^^^
    """.trimIndent()
    ), IsNotADependency {
        val adapters = module("apollo-adapters")
        ... // more modules here
    }
}
```

leading to a use site of:

```
implementation(ApolloGraphQL.apolloKotlin.runtime)
testImplementation(ApolloGraphQL.apolloKotlin.testingSupport)
androidTestImplementation(ApolloGraphQL.apolloKotlin.idlingResource)
```

----

I'm happy to go with either approach here, or @LouisCAD 's recommendation of `ApolloGraphQL.apollo3.runtime`.
Please let me know which is the preferred one.

**Comment by martinbonnin** [comment]
In retrospect, I think `com.apollographql.apollo3` as a package name was a mistake. I wish we could just have `apollo3.ApolloClient` like there is `okhttp3.OkHttpClient`, it's much more concise and beautiful. But anyways, it's all shipped now so too late to change this. 

I'm on the "terse" side of things:


```
implementation(Apollo3.api)
implementation(Apollo3.runtime)
```

But @LouisCAD proposal maps better to the maven GAV coordinates so it's working too. If there are rules in the `refreshProject` version, I'd just use them for consistency, if not terse version seems a bit more readable. In all cases, thanks for looking into this! :)

**Comment by LouisCAD** [comment]
If there was an apollo4, we can always reclaim the dependency notations as we have an auto-upgrade mechanism (which we already used a lot of times).

Therefore, I'd suggest `ApolloGraphQL.runtime` and alike, or `Apollo.runtime`, though both are a bit inconsistent with what we have for `Square.okHttp3`. The challenge here is that the library AND the authority have the same name, making things quite redundant.

**Comment by thederputy** [comment]
Thanks for the feedback!
I've gone with @LouisCAD 's naming suggestion of `ApolloGraphQL.runtime` and opened a PR to integrate the changes.
