### ISSUE TITLE
versions.properties is being updated during the processResources task

### ISSUE THREAD

**Issue by kaliy** [jmfayard/refreshVersions#526]
- [ x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug
Since 0.30.0 refreshVersions changes versions.properties files on build. In particular, it happens during the processResources task. 

Here is an example. This was the file that I had in 0.23.0. After the build it remains intact.

```
#### Dependencies and Plugin versions with their available updates.
#### Generated by `./gradlew refreshVersions` version 0.23.0
####
#### Don't manually edit or split the comments that start with four hashtags (####),
#### they will be overwritten by refreshVersions.
####
#### suppress inspection "SpellCheckingInspection" for whole file
#### suppress inspection "UnusedProperty" for whole file
plugin.io.spring.dependency-management=1.0.11.RELEASE
plugin.net.researchgate.release=2.8.1
plugin.org.datlowe.maven-publish-auth=2.0.2
plugin.org.springframework.boot=2.5.10
plugin.io.freefair.lombok=6.4.1
version.com.auth0..java-jwt=3.19.0
version.com.google.code.findbugs..jsr305=3.0.2
version.io.rest-assured..rest-assured-all=4.5.1
version.io.vavr..vavr=0.10.4
version.com.github.tomakehurst..wiremock-standalone=2.27.2
```

Then, after the upgrade to. 0.30.0 (and later) and running processResources file becomes like this:

```
#### Dependencies and Plugin versions with their available updates.
#### Generated by `./gradlew refreshVersions` version 0.30.0
####
#### Don't manually edit or split the comments that start with four hashtags (####),
#### they will be overwritten by refreshVersions.
####
#### suppress inspection "SpellCheckingInspection" for whole file
#### suppress inspection "UnusedProperty" for whole file

plugin.io.spring.dependency-management=1.0.11.RELEASE

plugin.net.researchgate.release=2.8.1

plugin.org.datlowe.maven-publish-auth=2.0.2

plugin.org.springframework.boot=2.5.10

plugin.io.freefair.lombok=6.4.1

version.com.auth0..java-jwt=3.19.0

version.com.google.code.findbugs..jsr305=3.0.2

version.io.rest-assured..rest-assured-all=4.5.1

version.io.vavr..vavr=0.10.4

version.com.github.tomakehurst..wiremock-standalone=2.27.2
```

As you can see, the header has been changed and the new lines were added. Actual version checking hasn't been performed.

For me it's a big problem as this file is preventing some git operations that happens in my project after the build process.

## ⚠️ Current behavior

versions.properties is being overwritten and reformatted after the processResources task

## ✅ Expected behavior
versions.properties should remain intact and only be changed when refreshVersions task is triggered

## 💣 Steps to reproduce

Just execute ./gradlew processResources with refreshVersions being included into settings.gradle

**Comment by LouisCAD** [comment]
Hello,
We need to update the versions.properties file after refreshVersions is updated because it's key in handling migrations when some dependency notations are removed.

I think you can make your git operations run `./gradlew`, or run it manually before committing to fix your specific setup.

**Comment by kaliy** [comment]
Ok, so it happens only when version.properties was created with a previous version of refreshVersions, correct?

For example, if I have version.roperties created with 0.40.1, reformatted it, then 0.40.1 won't change it but 0.40.2 would, correct?

**Comment by LouisCAD** [comment]
I'm not sure what you mean by formatted, but yes, it's a one time edit after upgrade and doesn't change afterwards unless you add a dependency or run the refreshVersions task.
