### ISSUE TITLE
Allow comments in the artifact version key rules files

### ISSUE THREAD

**Issue by toddobryan** [jmfayard/refreshVersions#528]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)

## ⚠️ Is your feature request related to a problem? Please describe

I've added rules for my dependencies that come in groups, but the file is pretty impenetrable.

## 💡 Describe the solution you'd like

It would be really nice if every line that started with, e.g., `#` were just ignored and could be used to comment.

## 🤚 Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

Tell me where the file is that parses the rules and I'll take a stab at it.

**Comment by imashnake0** [comment]
@toddobryan I personally never had the need to have comments but I always assumed they weren't handled. However, I did notice some comments [here](https://github.com/jmfayard/refreshVersions/blob/main/plugins/dependencies/src/main/resources/refreshVersions-rules/androidx-version-alias-rules.txt).

**Comment by toddobryan** [comment]
Ah, I tried #, since that's the comment character for properties files, but it looks like it uses double slash.

**Comment by imashnake0** [comment]
Yup, it's parsed [here](https://github.com/jmfayard/refreshVersions/blob/2fb560345c4db77ab44f5d333507573d0812d2d7/plugins/core/src/main/kotlin/de/fayard/refreshVersions/core/internal/ArtifactVersionKeysReading.kt#L28). Just so you know :)
