### ISSUE TITLE
Plugin configuration

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#53]
- **Available since: 0.4.2**
- **Version documented: 0.7.0**

## Add the plugin `de.fayard.refreshVersions` to your project

Edit your root `build.gradle(.kts)` file

[![pluginVersion](https://img.shields.io/maven-metadata/v/https/plugins.gradle.org/m2/de.fayard/buildSrcVersions/de.fayard.buildSrcVersions.gradle.plugin/maven-metadata.xml.svg?label=gradlePluginPortal)](https://plugins.gradle.org/plugin/de.fayard.buildSrcVersions)

```kotlin
plugins {
  id("de.fayard.refreshVersions") version "$VERSION"
}
// Don't put any code before the buildscript {} and plugins {} block

// See configuration options at https://github.com/jmfayard/buildSrcVersions/issues/53
buildSrcVersions {
    
}
```

Used `de.fayard.buildSrcVersions` before? See [Long term plan: focus on refreshVersions](https://github.com/jmfayard/buildSrcVersions/issues/104)

The configuration options are described in [#53 Plugin Configuration](https://github.com/jmfayard/buildSrcVersions/issues/53)

You can find the latest `$VERSION` at https://plugins.gradle.org/plugin/de.fayard.refreshVersions

## Default configuration

```kotlin
/**
 * Use ./gradlew refreshVersions to find available updates
 * See https://github.com/jmfayard/buildSrcVersions/issues/77
 *
 * Use ./gradlew buildSrcVersions to generate buildSrc/src/main/Libs.kt
 * See https://github.com/jmfayard/buildSrcVersions/issues/88
 */
buildSrcVersions {
    // See configuration options at https://github.com/jmfayard/buildSrcVersions/issues/53    

    rejectVersionIf {
      isNonStable(candidate.version)
    }
    //alwaysUpdateVersions()
    orderBy = OrderBy.GROUP_AND_LENGTH
    versionsOnlyMode = null
    versionsOnlyFile = null
    indent = null
    renameLibs = "Libs"
    renameVersions = "Versions"
    useFqdnFor() // nothing

}
```

## Things you can configure

- `orderBy = OrderBy.GROUP_AND_ALPHABETICAL` to sort `gradle.properties` in alphabetical order. 
- `indent = "\t"` to use tabs instead of spaces in the generated code. Note that since v0.5.0, the indent is auto-detected if you have a by a [EditorConfig file](https://editorconfig.org)
- `renameLibs = "Deps"` to generate `Deps.kt` instead of `Libs.kt`
- `renameVersions = "V"` to generate `V.kt` instead of `Versions.kt`
- `useFqdnFor("mail", "annotations", "androidx.persistence.room", "androidx.persistence")`. Using `Libs.annotations` may not make sense out of context. With this config it will be `Libs.com_example_group_annotations`. Some [MEANING_LESS_NAMES](https://github.com/jmfayard/buildSrcVersions/blob/master/plugin/src/main/kotlin/de/fayard/internal/PluginConfig.kt#L86-L95) like "library" or "compiler" are pre-configured.

## Which versions to reject?

Use your custom [`rejectVersionIf { ... }`](https://github.com/ben-manes/gradle-versions-plugin/issues/325
)

```kotlin
rejectVersionIf {
    isStable(currentVersion) && isNonStable(candidate.version)
}
```

You can even define your own function [`isNonStable()`](https://github.com/jmfayard/buildSrcVersions/blob/master/plugin/src/main/kotlin/de/fayard/internal/PluginConfig.kt#L26-L35) if the default one does not work for your project.

## versionsOnlyMode

The plugin has since v0.5.0 a `versionsOnlyMode` for single-module Gradle projects. This is what powers the task `:refreshVersions` introduced in version v0.6.0

```kotlin
// build.gradle.kts
buildSrcVersions {
   versionsOnlyMode = VersionsOnlyMode.GRADLE_PROPERTIES
   versionsOnlyFile = "build.gradle"
}
```

`versionsOnlyMode` is an enum:
 
- [`KOTLIN_VAL`](https://github.com/jmfayard/buildSrcVersions/blob/master/sample-versionsOnlyMode/KOTLIN_VAL.gradle.kts) will generate `val okhttp = "3.2.0"`
- [`KOTLIN_OBJECT`](https://github.com/jmfayard/buildSrcVersions/blob/master/sample-versionsOnlyMode/KOTLIN_OBJECT.kt) will generate the same file as `Versions.kt` in the default mode
- [`GROOVY_DEF`](https://github.com/jmfayard/buildSrcVersions/blob/master/sample-versionsOnlyMode/GROOVY_DEF.gradle) will generate `def okhttp = '3.2.0'`
- [`GROOVY_EXT`](https://github.com/jmfayard/buildSrcVersions/blob/master/sample-versionsOnlyMode/GROOVY_EXT.gradle) will generate `ext { okhttp = '3.2.0' } `
- [`GRADLE_PROPERTIES`](https://github.com/jmfayard/buildSrcVersions/blob/master/sample-versionsOnlyMode/GRADLE_PROPERTIES.properties) will generate `okhttp=3.2.0`

## Migration // Deprecation 

*Breaking changes:*

Those configurations were marked as deprecated in 0.5.0 and removed in 0.6.0

```kotlin
buildSrcVersions {
    useFdqnFor = ... // typo, use useFqdnFor()
    useFdqnFor(...)  // typo, use useFqdnFor()
    rejectedVersionKeywords = ... // use rejectVersionIf { ... }
    rejectedVersionKeywords(...)  // use rejectVersionIf { ... }
}
```

## Note for contributors: 

New features should probably be an opt-in. If you do this, add a property to `BuildSrcVersionsExtension`, use it in the samples, document the default value in the `README` and with more details in this issue.

**Comment by jschneider** [comment]
Configure use of fully qualified name like that:
`useFdqnFor("mail", "com.intellij:annotations", "annotations", "it_test_support")`

**Comment by jmfayard** [comment]
Thanks

**Comment by jmfayard** [comment]
Documentation updated for v0.5.0

**Comment by jmfayard** [comment]
Documentation updated for `v0.6.0` and the new feature
- #77 `./gradle :refreshVersions` generates gradle.properties with versions and available updates

**Comment by PaulWoitaschek** [comment]
Is there a way to specify which `com.github.ben-manes.versions` version this plugin uses?

**Comment by jmfayard** [comment]
Not currently. I tried in a project to force to use a newer version than the one in the plug-in but that didn't work

**Comment by LouisCAD** [comment]
@jmfayard Isn't this issue obsolete?

**Comment by jmfayard** [comment]
It is
