### ISSUE TITLE
Dependency notations for Ktor 2.0.0

### ISSUE THREAD

**Issue by brady-aiello** [jmfayard/refreshVersions#538]
## New Ktor libraries

- *Description*: We already have libraries for Ktor, but Ktor 2.0.0 renames several libraries, adds new ones, and our implementation doesn't have all the original ones either. This is the best reference on changes from 1.6.x to 2.0.0:
https://ktor.io/docs/migrating-2.html
- *GitHub*: https://github.com/ktorio/ktor
- *Official website* https://ktor.io/

## Want to contribute the sample?
Yes, I'll submit the PR.

**Comment by jmfayard** [comment]
This has been solved in https://github.com/jmfayard/refreshVersions/commit/7190b6fed2d1631e3d964302d415c80d54bc40a4
