### ISSUE TITLE
[Bug] Not resolving dependency stability properly

### ISSUE THREAD

**Issue by solonovamax** [jmfayard/refreshVersions#551]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug
Fails to properly set `StabilityLevel` for a dependency on [jgit](https://www.eclipse.org/jgit/).

## ⚠️ Current behavior
Currently, the following versions are resolved incorrectly:

- `6.1.0.202203080745-r`: `StabilityLevel.Unknown`
- `5.0.0.201805151920-m7`: `StabilityLevel.Unknown`

## ✅ Expected behavior

They should be resolved as follows:
- `6.1.0.202203080745-r`: `StabilityLevel.Stable`
- `5.0.0.201805151920-m7`: `StabilityLevel.Milestone`

## 💣 Steps to reproduce
Add the following `versions.properties` file:
```properties
version.jgit=6.0.0.202111291000-r
```
and the following code to your `settings.gradle.kts`:
```kotlin
import de.fayard.refreshVersions.core.StabilityLevel

/* [...] */

plugins {
    id("de.fayard.refreshVersions") version "0.40.2"
}
refreshVersions {
    extraArtifactVersionKeyRules("""
            org.eclipse.jgit:org.eclipse.jgit
                                         ^^^^
    """.trimIndent())
    
    rejectVersionIf {
        @Suppress("UnstableApiUsage")
        candidate.stabilityLevel != StabilityLevel.Stable
    }
}
```
(of course, make sure to depend on it somewhere)

You should *expect* to see refreshVersions suggest upgrading to `6.1.0.202203080745-r`, as it does without the `rejectVersionIf` rule.

**Comment by jmfayard** [comment]
Hello @solonovamax 
thank you for your PR here https://github.com/jmfayard/refreshVersions/pull/552

But I'm not too keen on that particular solution of having "suffixes known to be stable".
You have no idea how creative and weird developers are with their naming schema.
Just think about `git` where odd and even numbers means stability,
or `tex` and `latext` which uses the decimals of `e` and `pi` (I think).
So I hope that you understand that I don't want to go inside this rabbit hole.

There is an alternative though.

You can do 

```kotlin
    rejectVersionIf {
        val isWeird =  versionKey == "version.jgit"
        !isWeird && candidate.stabilityLevel != StabilityLevel.Stable
    }
```

What do you think?

**Comment by solonovamax** [comment]
@jmfayard the reason why I felt like it warranted a change to the source was simply because appending `-r` to a version doesn't seem that ""out there"", as opposed to git's "odd vs even numbers" or tex's "number's of pi" (TeX uses the numbers of pi, LaTeX uses a more "standard" approach)
I recall previously seeing adding a `-r` to a version somewhere else (though, I cannot remember where off the top of my head), but it definitely feels common enough that it should be added.

I understand not wanting to deal with "every edge case under the sun", I just feel given that "-r" stands for "-release", it makes enough sense to be added.

**Comment by LouisCAD** [comment]
@jmfayard For this issue, I'm thinking about removing `StabilityLevel.Unknown`, and considering lowercase `m` as a milestone marker, just like the uppercase `M`.

That should be enough to fix it I think.
That should also fix the no longer relevant problem of `native-mt` coroutines artifacts that were shown as older than the regular one because of the sorting by stability level.

Do you think that `StabilityLevel.Unknown` is of any use over treating anything that didn't match our "almost-stable" criterions as stable, getting the `StabilityLevel.Stable` label?
