### ISSUE TITLE
Excessive memory usage in multi-module project

### ISSUE THREAD

**Issue by chelbanv** [jmfayard/refreshVersions#554]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug

The plugin is leaking memory during gradle build phase. 
During the execution phase of our gradle build this plugin is keeping a huge amount of heap memory allocated, even though it's past the configuration phase. 

## ⚠️ Current behavior

The plugin holds up memory during build execution phase. Even during R8 minification phase.
Here is a snapshot from a heap dump and analyzed with Eclipse MAT, pointing to this plugin as being the primary suspect for a considerable memory leak. 
<img width="661" alt="Screenshot 2022-06-22 at 15 20 39" src="https://user-images.githubusercontent.com/91326884/175054902-b38ed5f2-273a-4e53-8ee5-38601c2a1c06.png">

More details (shortest path - dominator tree):
<img width="1038" alt="Screenshot 2022-06-22 at 15 22 04" src="https://user-images.githubusercontent.com/91326884/175055835-595019c1-c58e-4047-97ed-035e588326aa.png">

Repeated run:
it's simply accumulating memory without releasing it - that's leaking. 

<img width="966" alt="Screenshot 2022-06-22 at 16 01 19" src="https://user-images.githubusercontent.com/91326884/175063453-9fa56fa4-80ac-4c57-b15d-477f50e64d67.png">

## ✅ Expected behavior

The plugin shouldn't hold-up big chunks of allocated memory during the build execution phase. 

## 💣 Steps to reproduce

* Android multi-module Project with dynamic plugin applied 
* 40+ modules
* each module has 10-50 dependencies in the `dependencies` block
* the gradle build task is called (a release variant, which uses minification/R8)
* I took a heap dump at the beginning of the build and during the R8 build. They both seem to be occupying the same memory space (around 800 MB). 

## 📱 Tech info
 - [Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg): 
Private repo - can't provide this

**Comment by LouisCAD** [comment]
Hello, which version of refreshVersions are you using?

**Comment by chelbanv** [comment]
Hi. We're using `0.40.1`.
I just noticed the `0.40.2` version, which contains the fix. I'll give it a try and see if still reproduces.

**Comment by chelbanv** [comment]
I verified. The leak is fixed in `0.40.2`. Thanks 🙏
