### ISSUE TITLE
Androidx media3 datasource vs dataSource

### ISSUE THREAD

**Issue by yschimke** [jmfayard/refreshVersions#565]
## 🐛 Describe the bug

both dataSource and datasource show up in completion

## ⚠️ Current behavior

dataSource is standalone, datasource is a group.

## ✅ Expected behavior

Like ui, ui. completes to children.

## 💣 Steps to reproduce

See https://github.com/jmfayard/refreshVersions/blob/main/plugins/dependencies/src/main/kotlin/dependencies/AndroidX.kt#L1860

**Comment by LouisCAD** [comment]
Nice catch, it looks like we missed it while reviewing our work on AndroidX dependency notations.

it should be a `DependencyNotationAndGroup`. I'll fix it for the next release.
