### ISSUE TITLE
Review bundled dependencies from #559

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#568]
We want to do small and fast PR but that was not the case of #559 who grew to be too big and stale.
So I merged it and created this issue so that @LouisCAD can check a posteriori whether the following dependencies are OK

- Jetbrains.exposed.*
- Ktor2.*
- KotlinX.lincheck.*
- KotlinX.multik.*
- KotlinX.dataframe.*
- KotlinX.deeplearning.*
- Koin.navigation
-  Kotlinx.dataframe
-    Testing.cucumber
-    Testing.assertj
-    Testing.jsonAssert
-    Testing.powermock
-    Testing.restAssured

**Comment by jmfayard** [comment]
- Arrow: review if missing dependencies https://search.maven.org/search?q=a:arrow-stack
- KotlinX: remove dataframe.gradlePlugin
- KotlinX: remove import
- Spring: remove boms.springclmoud
- Square.okhttp3: move comments to Kdoc
- Ktor: remove Ktor1 vs Ktor2, use built-in mechanism, add this comment `// TODO: Migrate to ktor2. See https://ktor.io/docs/migrating-2.html`
- Testing.kotest.kotestExtensions => move to kotestProperty and check if version is the same for both dependencies. I think it's not
- Remove `val jsonAssert = DependencyNotation("org.skyscreamer", "jsonassert")`
- Remove `Testing.cucumber` because too many dependencies/versions available at https://search.maven.org/search?q=g:io.cucumber
- Remove `Testing.powermock`


**Not for now**

how to handle third party DN like for Ktor2 plugins?

**Comment by LouisCAD** [comment]
I think Ktor2 version key rules were also forgotten. I'm adding them back.
