### ISSUE TITLE
HTTP 409 when resolving plugin 0.41.0-SNAPSHOT

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#570]
Not sure what the problem is, not urgent, writing it down here for future reference

Snapshot configured like in https://jmfayard.github.io/refreshVersions/setup/#if-you-want-to-use-a-snapshot-version

```bash
$ ./gradlew -refresh-dependencies refreshVersionsCatalog --versions --all --scan
> Could not resolve all files for configuration ':buildSrc:compileClasspath'.
  > Could not resolve de.fayard.refreshVersions:de.fayard.refreshVersions.gradle.plugin:0.41.0-SNAPSHOT.
    Required by:
        project :buildSrc
    > Could not resolve de.fayard.refreshVersions:de.fayard.refreshVersions.gradle.plugin:0.41.0-SNAPSHOT.
      > Could not get resource 'https://plugins.gradle.org/m2/de/fayard/refreshVersions/de.fayard.refreshVersions.gradle.plugin/0.41.0-SNAPSHOT/de.fayard.refreshVersions.gradle.plugin-0.41.0-SNAPSHOT.pom'.
        > Could not HEAD 'https://repo.gradle.org/artifactory/jcenter/de/fayard/refreshVersions/de.fayard.refreshVersions.gradle.plugin/0.41.0-SNAPSHOT/de.fayard.refreshVersions.gradle.plugin-0.41.0-SNAPSHOT.pom'. Received status code 409 from server: Conflict
```

I don't understand why it searches the snapshot version in gradlePluginPortal() instead of `maven("https://s01.oss.sonatype.org/content/repositories/snapshots")` which is configured correctly.

See error at  https://scans.gradle.com/s/qr75gfx7bjcng/failure#1

**Comment by LouisCAD** [comment]
It's similar to https://github.com/jmfayard/refreshVersions/issues/557, you need to setup the repo for buildSrc too.

**Comment by jmfayard** [comment]
You're right, that's confusing
