### ISSUE TITLE
Required value 'version' missing at $

### ISSUE THREAD

**Issue by shafty023** [jmfayard/refreshVersions#576]
## 🐛 Describe the bug
Attempt to run ./gradlew refreshVersions and receive the above error

## ⚠️ Current behavior
Unable to run refreshVersions gradle task.
Sometimes receive "Required value 'version' missing at $" and other times receive "java.io.InterruptedIOException: executor rejected". The latter can be fixed by running ./gradlew --stop. The former I have not found a solution.

## ✅ Expected behavior
Expected to be able to run refreshVersions task

## 💣 Steps to reproduce
Run ./gradlew refreshVersions from cli or Android Studio

## 📱 Tech info
gradle 6.8
jdk 11
build.gradle not build.gradle.kts

**Comment by jmfayard** [comment]
I'm sorry but without reproducing steps, I can't do much :(

**Comment by LouisCAD** [comment]
No stacktrace, no reproducer, no Gradle scan link, no hint, how would you fix it if you were in our boots @shafty023? 😉

We'll happily re-open when we'll get an update from you 🙂
