### ISSUE TITLE
Constraint layout and core constraint layout dependencies conflict

### ISSUE THREAD

**Issue by Swisyn** [jmfayard/refreshVersions#578]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug
I have constraintlayout and constraintlayout-core dependencies in our app. Both of them have different versions (constraintlayout:2.1.4 and constraintlayout-core:1.0.4)

## ⚠️ Current behavior
Plugin considers these dependencies as same, and marks the -core one as unused. Even though it'se used and declared in the `build.gradle.kts` of the app.

## ✅ Expected behavior
Plugin should considers these dependencies as separate, as they're.

## 💣 Steps to reproduce
Declare these 2 dependencies in `Dependencies.kt`

```
    const val androidxConstraintLayoutCore = "androidx.constraintlayout:constraintlayout-core:${Versions.androidxConstraintLayoutCore}"
    const val androidxConstraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.androidxConstraintLayout}"
```

and their versions in `Versions.kt`
```
    const val androidxConstraintLayoutCore = "_"
    const val androidxConstraintLayout = "_"

```

project won't build.

## 📱 Tech info
 - Exception strack trace
 
9: Task failed with an exception.
-----------
```
* What went wrong:
Execution failed for task ':app:mergeSandboxNativeLibs'.
> Could not resolve all files for configuration ':app:sandboxRuntimeClasspath'.
   > Could not find androidx.constraintlayout:constraintlayout-core:2.1.4.
     Searched in the following locations:
       - /androidx/constraintlayout/constraintlayout-core/2.1.4/constraintlayout-core-2.1.4.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :app
   > Could not find androidx.constraintlayout:constraintlayout-core:2.1.4.
     Searched in the following locations:
       - https://nexus.es.ecg.tools/repository/ek-android/androidx/constraintlayout/constraintlayout-core/2.1.4/constraintlayout-core-2.1.4.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :app > androidx.constraintlayout:constraintlayout:2.1.4

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

**Comment by LouisCAD** [comment]
Hello, I acknowledge this issue and I got a fix. However, I'm wondering what you're using `constraintlayout-core` for as it's not documented and should not be needed if you use it with Views or Composables.

**Comment by Swisyn** [comment]
@LouisCAD I really appreciate for the fix! Actually that was already implemented from someone else in our project, I just wanted to automate our dependency update process with `refreshVersions` plugin and then faced with this issue.
