### ISSUE TITLE
Add integration tests with gradleTestKit()

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#59]
It would be useful to have integration tests powered by gradleTestKit().

For example that would allow to test the plugin with different versions of Gradle like https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy

Documentation:

- [gradle-site-plugin](https://github.com/gradle-guides/gradle-site-plugin)
- [Testing Build Logic with TestKit](https://docs.gradle.org/current/userguide/test_kit.html)
- https://github.com/ben-manes/gradle-versions-plugin/tree/master/src/test
- [Embedding Gradle using the Tooling API](https://docs.gradle.org/current/userguide/embedding.html#embedding)
- [GradleConenctor](https://docs.gradle.org/current/javadoc/org/gradle/tooling/GradleConnector.html)
- [Developing Custom Gradle Plugins](https://docs.gradle.org/current/userguide/custom_plugins.html)

**Comment by jmfayard** [comment]
The GitHub + Gradle actions do the same work so closing this

**Comment by LouisCAD** [comment]
Gradle Test Kit doesn't support Settings plugins, so we can't use it in refreshVersions.
