### ISSUE TITLE
Documentation: Update terminology for latest IntelliJ version

### ISSUE THREAD

**Issue by thederputy** [jmfayard/refreshVersions#621]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug
Terminology change inside IntelliJ for including a new Gradle project.

## ⚠️ Current behavior
The [Dev environment documentation](https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dev-env/#import-the-plugins-gradle-project) states that you should Select "Import Gradle Project"

## ✅ Expected behavior
As of at least IntelliJ 2022.2.1, the menu option has changed to "Link Gradle Project"

## 💣 Steps to reproduce
Follow  the [Dev environment documentation](https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dev-env/#import-the-plugins-gradle-project) and compare to the latest IntelliJ

## 📱 Tech info
N/A

**Comment by LouisCAD** [comment]
For trivial changes like that, where you're 90% sure we're going to accept them, and especially if you've already made the changes, no need to create an issue, you can submit the PR directly 😉
