### ISSUE TITLE
rejectVersionIf { } now considers all versions as stable

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#629]
## 🐛 Describe the bug

In refreshVersions 0.50.2, all versions are described as stable

## ⚠️ Current behavior

Versions like 1.7.20-RC and 1.7.20-Beta are considered stable.
rendering `refreshVersions.rejectVersionIf { .. }` useless

## ✅ Expected behavior

Like before

## 💣 Steps to reproduce

Checkout https://github.com/jmfayard/kotlin-playground/commit/0e07f639e826b7a7bc2d7de14c8df4155bee55f0

## 📱 Tech info

https://scans.gradle.com/s/dteblugtek5ec#infrastructure

**Comment by LouisCAD** [comment]
Oh yeah, we need to support number-less versions.

Care to add some failing tests in a PR? I'd pick it up from here and fix it the way it should.

**Comment by LouisCAD** [comment]
Fixed on main, just launched the publication of a new snapshot in case you want to try it before one of use make a new release.
