### ISSUE TITLE
SocketTimeOut refreshVersions depends on missing moshi artifact

### ISSUE THREAD

**Issue by mochadwi** [jmfayard/refreshVersions#643]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug

<img width="1378" alt="Screen Shot 2022-10-31 at 1 44 25 PM" src="https://user-images.githubusercontent.com/7057959/198947544-03229056-4c28-45ab-88c5-6579423f2880.png">

## ⚠️ Current behavior

Due to moshi missing from this directory: https://plugins.gradle.org/m2/com/squareup/moshi/moshi-kotlin/1.11.0/moshi-kotlin-1.11.0.module (403 forbidden), therefore when trying to build our apps in Github Actions the above screenshot happened.

## ✅ Expected behavior

Able to continue to building process

## 💣 Steps to reproduce

We're not sure how to reproduce this. We runs gradle task with following commands:

```
gradlew assembleStagingDebug -p . -PCI_PIPELINE_ID=00 -PBUILD_VARIANT=StagingDebug -Dorg.gradle.jvmargs=-Xmx6g --stacktrace --build-cache --scan --no-daemon
```

## 📱 Tech info
 - [Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg): 

In progress how to repro this in our local, somehow in our Github Actions, unable to publish the build scan :pray:

**Comment by jmfayard** [comment]
There is a jcenter outage right now and gradle plugin portal depends on it

That may be the issue

https://status.gradle.com/?_ga=2.115735174.1498944834.1667201420-1296576817.1667201420

**Comment by mochadwi** [comment]
i see, thanks for confirming, it flew of my radar about the gradle status, closing this issue as not related to refreshversion 🙏 , as one of our CI now passed
