### ISSUE TITLE
 Must be configured in settings.gradle(.kts), not in build.gradle(.kts)

### ISSUE THREAD

**Issue by YunaBraska** [jmfayard/refreshVersions#674]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug
>  `./gradlew refreshVersions` 
```
FAILURE: Build failed with an exception.

* Where:
Build file 'build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'de.fayard.refreshVersions', version: '0.51.0']
> Failed to apply plugin 'de.fayard.refreshVersions'.
   > plugins.id("de.fayard.refreshVersions") must be configured in settings.gradle(.kts), not in build.gradle(.kts).
     See https://jmfayard.github.io/refreshVersions/setup/

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 353ms
```

## ⚠️ Current behavior
Does not work out of the box. Entering `./gradlew refreshVersions`  returns the error `plugins.id("de.fayard.refreshVersions") must be configured in settings.gradle(.kts), not in build.gradle(.kts).`

## ✅ Expected behavior
Should work out of the box

## 💣 Steps to reproduce
1) Setup Gradle 7.6
2) Create a simple `build.gradle` with `spring boot 3`
3) Add `id 'de.fayard.refreshVersions' version '0.51.0'` to  `build.gradle`
3) Run `./gradlew refreshVersions`
4) Receive error

## 📱 Tech info
```
------------------------------------------------------------
Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.1 (Azul Systems, Inc. 17.0.1+12-LTS)
OS:           Mac OS X 13.2.1 aarch64
```

**Comment by LouisCAD** [comment]
Have you read the error message though?

**Comment by LouisCAD** [comment]
What would you expect if you plugged an electrical appliance to a pipe or a tap that serves water?

I don't work to come off as rude, but we made a pretty clear error message already, the solution is there.

**Comment by YunaBraska** [comment]
@LouisCAD no idea what you have smoked, but that wasn’t an Answer. So what’s the issue then?
I can only assume that I need ‘kts’ which sounds actually optional in the error message.

welcome to open source, everyone is just mad at you. Next time I open a bug ticket and just write “doesn’t work”
I wish that your repo doesn’t get popular!

**Comment by LouisCAD** [comment]
I purposefully wrote the error message so we don't waste time with config issues, and yet, here we are.
It even includes a link to the setup doc. Read it thoroughly.

If after reading it, and after trying to understand what the error message meant, you still don't get it, then I'd advise you to upskill your English.

**Comment by LouisCAD** [comment]
Also, screw you for your mean messages and trolls. I'm not even paid for that.

**Comment by YunaBraska** [comment]
@LouisCAD Your Action and my reaction... AS you do Open Source you should know better how to treat people.
Well, we don't have to use your library. Thx for no help.
