### ISSUE TITLE
./gradlew buildSrcVersions

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#88]
# UPDATE : Documentation below doesn't reflect current dev
**Development shifted to the `refreshVersions` and `dependencies` gradle plugins, the buildSrcVersions plugin is no longer under development.**

----

<img src="https://github.com/jmfayard/buildSrcVersions/raw/master/doc/carbon-Libs-Versions.png"></img>

**Available since: 0.4.0**

**Modified in v0.6.2**

The plugin `de.fayard.buildSrcVersions` has now two tasks. 

- [The new task  `:refreshVersions`](https://github.com/jmfayard/buildSrcVersions/issues/77) task provides *just the versions and their available updates* and is a good solution for simple, single-module Gradle projects.
- The task `:buildSrcVersions` still exists and is a good solution for complex multi-module Gradle projects: Android, Kotlin multi-platform, ...

# Getting Started

## Add the plugin `de.fayard.buildSrcVersions` to your project

Edit your root `build.gradle(.kts)` file

[![pluginVersion](https://img.shields.io/maven-metadata/v/https/plugins.gradle.org/m2/de.fayard/buildSrcVersions/de.fayard.buildSrcVersions.gradle.plugin/maven-metadata.xml.svg?label=gradlePluginPortal)](https://plugins.gradle.org/plugin/de.fayard.buildSrcVersions)

```kotlin
buildscript {
}
plugins {
  id("de.fayard.buildSrcVersions") version "$VERSION"
}
// Don't put any code before the buildscript {} and plugins {} block

// See configuration options at https://github.com/jmfayard/buildSrcVersions/issues/53
buildSrcVersions {
    
}
```

The configuration options are described in [#53 Plugin Configuration](https://github.com/jmfayard/buildSrcVersions/issues/53)

You can find the latest `$VERSION` at https://plugins.gradle.org/plugin/de.fayard.buildSrcVersions

## Run `:refreshVersions` to extract your versions

New in v0.6.2: the task :refreshVersions extract your versions in gradle.properties 

[Read the docs](https://github.com/jmfayard/buildSrcVersions/issues/77)

If you choose to use `:refreshVersions`, then `Versions.kt` is not generated anymore (it's less efficient since every change requires all the tasks to be recompiled), but you can still use `Libs.kt` to re-use your dependencies.

## Run `:buildSrcVersions` to extract your dependencies

The plugin adds a task to your build, also called `:buildSrcVersions`. Run it like this:

```bash
$ ./gradlew buildSrcVersions
> Task :dependencyUpdates
> Task :buildSrcVersions
        new file:   buildSrc/build.gradle.kts
        new file:   buildSrc/.gitignore
        new file:   buildSrc/settings.gradle.kts
        new file:   buildSrc/src/main/kotlin/Libs.kt
        new file:   buildSrc/src/main/kotlin/Versions.kt
```

## Replace your dependencies

![](https://github.com/jmfayard/buildSrcVersions/blob/master/doc/Libs.gif?raw=true)

Synchronize your Gradle build.

You can now start to replace your magic strings with the properties available in [`Libs.kt`](https://github.com/jmfayard/buildSrcVersions/blob/e117dc0898aadbc1fce1029a87c48d5aa0ce269c/doc/Libs.kt) 

```kotlin
dependencies {
    implementation(Libs.okio)
    implementation(Libs.com_squareup_moshi_moshi)
}
```

Once you have replaced your magic strings by `Libs.xxx`, the main feature provided by this plugin is to search for dependencies updates.

# Search for dependencies updates

## This is important

Upgrade dependencies tend to be tedious but it is critically important:

- Few projects have versioned documentation: master/README.md is their documentation. This means you can waste time trying out snippets that do not work in the version you are using.
- When you open an issue, you will often be asked: Can you reproduce this problem in the latest version?
- On the other hand, you don’t want to break your app because there was a breaking change and you didn’t bother to read the CHANGELOG documenting it.

This plugin inherits from the {benmanes}[Gradle Versions plugin^]
the feature to automatically determine which dependencies have updates.

## Run again `:buildSrcVersions`

When you decide you want to update some dependencies, run again the plugin:

```bash
$ ./gradlew buildSrcVersions
> Task :dependencyUpdates
> Task :buildSrcVersions
        modified:   buildSrc/src/main/kotlin/Libs.kt
        modified:   buildSrc/src/main/kotlin/Versions.kt

```

The file [`Versions.kt`](https://github.com/jmfayard/buildSrcVersions/blob/e117dc0898aadbc1fce1029a87c48d5aa0ce269c/doc/Versions.kt)  is regenerated with a comment indicating which new version is available.

At that point, your build is exactly the same. Commit.

![](https://github.com/jmfayard/buildSrcVersions/blob/master/doc/Versions.gif?raw=true)

Don’t waste your time finding out manually what is the exact latest stable version available. Instead, spend it deciding whether you want or not to update the version. The format is optimized to update with one DELETE key:

![image](https://user-images.githubusercontent.com/459464/65773130-f4ecf200-e13b-11e9-9106-333f678a089a.png)

Once you are done:

- Sync your Gradle build
- Run your unit tests and otherwise verify that it works.
- Commit.

##  Configuration

No configuration is required, but some things are configurable.

The default configuration is:

```
// See Plugin configuration at https://github.com/jmfayard/buildSrcVersions/issues/53
buildSrcVersions {
    indent = "  "
    renameLibs = "Libs"
    renameVersions = "Versions"
    useFdqnFor() // nothing
}
```

See https://github.com/jmfayard/buildSrcVersions/issues/53[Issue #53: Plugin Configuration]

# More

## Try out the samples

If you want to test the plug-in quickly, the repository contains three samples just for this. They are also very handy to report a bug.

```bash
$ git clone https://github.com/jmfayard/buildSrcVersions
$ cd buildSrcVersions/sample-kotlin
$ ./gradlew run -q
> Task :run
Guava says: mean(4, 2)=3.0
```

## Is it magic?

No.

See [#70 How does it work? Is it magic?](https://github.com/jmfayard/buildSrcVersions/issues/79)
 
## Configuring Gradle with the `gradle.properties` file

In order to make it even easier to upgrade a project, here is an overview of settings that can be used in gradle.properties. 

[Configuring Gradle with the `gradle.properties` file](https://dev.to/jmfayard/configuring-gradle-with-gradle-properties-211k)

It's hard to find an overview of this information so I thought I would provide it

**Comment by LouisCAD** [comment]
Closing as obsolete regarding the state of the project.
